//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AutomationEntities : DbContext
    {
        public AutomationEntities()
            : base("name=AutomationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int spr_tblLetterActionTypeDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblLetterActionTypeDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblLetterActionTypeInsert(string fldTitleActionType, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc, string fldIP)
        {
            var fldTitleActionTypeParameter = fldTitleActionType != null ?
                new ObjectParameter("fldTitleActionType", fldTitleActionType) :
                new ObjectParameter("fldTitleActionType", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblLetterActionTypeInsert", fldTitleActionTypeParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_tblLetterActionTypeUpdate(Nullable<int> fldId, string fldTitleActionType, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldTitleActionTypeParameter = fldTitleActionType != null ?
                new ObjectParameter("fldTitleActionType", fldTitleActionType) :
                new ObjectParameter("fldTitleActionType", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblLetterActionTypeUpdate", fldIdParameter, fldTitleActionTypeParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_tblErrorInsert(ObjectParameter fldID, string fldUserName, string fldMatn, Nullable<System.DateTime> fldTarikh, string fldIP, Nullable<int> fldUserId, string fldDesc)
        {
            var fldUserNameParameter = fldUserName != null ?
                new ObjectParameter("fldUserName", fldUserName) :
                new ObjectParameter("fldUserName", typeof(string));
    
            var fldMatnParameter = fldMatn != null ?
                new ObjectParameter("fldMatn", fldMatn) :
                new ObjectParameter("fldMatn", typeof(string));
    
            var fldTarikhParameter = fldTarikh.HasValue ?
                new ObjectParameter("fldTarikh", fldTarikh) :
                new ObjectParameter("fldTarikh", typeof(System.DateTime));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblErrorInsert", fldID, fldUserNameParameter, fldMatnParameter, fldTarikhParameter, fldIPParameter, fldUserIdParameter, fldDescParameter);
        }
    
        public virtual int spr_tblLetterActionsInsert(Nullable<long> fldLetterId, Nullable<int> fldLetterActionTypeId, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc, string fldIP)
        {
            var fldLetterIdParameter = fldLetterId.HasValue ?
                new ObjectParameter("fldLetterId", fldLetterId) :
                new ObjectParameter("fldLetterId", typeof(long));
    
            var fldLetterActionTypeIdParameter = fldLetterActionTypeId.HasValue ?
                new ObjectParameter("fldLetterActionTypeId", fldLetterActionTypeId) :
                new ObjectParameter("fldLetterActionTypeId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblLetterActionsInsert", fldLetterIdParameter, fldLetterActionTypeIdParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblLetterFileMojazSelect> spr_tblLetterFileMojazSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblLetterFileMojazSelect>("spr_tblLetterFileMojazSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_tblLetterActionsSelect> spr_tblLetterActionsSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblLetterActionsSelect>("spr_tblLetterActionsSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_tblLetterActionTypeSelect> spr_tblLetterActionTypeSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblLetterActionTypeSelect>("spr_tblLetterActionTypeSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_tblErrorSelect> spr_tblErrorSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblErrorSelect>("spr_tblErrorSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_tblReferralRulesSelectRecivers> spr_tblReferralRulesSelectRecivers(string fieldname, string value, Nullable<int> h, Nullable<int> fldCommisionId)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            var fldCommisionIdParameter = fldCommisionId.HasValue ?
                new ObjectParameter("fldCommisionId", fldCommisionId) :
                new ObjectParameter("fldCommisionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblReferralRulesSelectRecivers>("spr_tblReferralRulesSelectRecivers", fieldnameParameter, valueParameter, hParameter, fldCommisionIdParameter);
        }
    
        public virtual ObjectResult<spr_tblHistoryTypeSelect> spr_tblHistoryTypeSelect(string fieldname, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblHistoryTypeSelect>("spr_tblHistoryTypeSelect", fieldnameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblLetterFileMojazDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblLetterFileMojazDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblLetterFileMojazInsert(Nullable<int> fldFormatFileId, Nullable<byte> fldType, Nullable<int> fldUserId, string fldDesc, Nullable<int> fldOrganId, string fldIP)
        {
            var fldFormatFileIdParameter = fldFormatFileId.HasValue ?
                new ObjectParameter("fldFormatFileId", fldFormatFileId) :
                new ObjectParameter("fldFormatFileId", typeof(int));
    
            var fldTypeParameter = fldType.HasValue ?
                new ObjectParameter("fldType", fldType) :
                new ObjectParameter("fldType", typeof(byte));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblLetterFileMojazInsert", fldFormatFileIdParameter, fldTypeParameter, fldUserIdParameter, fldDescParameter, fldOrganIdParameter, fldIPParameter);
        }
    
        public virtual int spr_tblLetterFileMojazUpdate(Nullable<int> fldId, Nullable<int> fldFormatFileId, Nullable<byte> fldType, Nullable<int> fldUserId, string fldDesc, Nullable<int> fldOrganId, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldFormatFileIdParameter = fldFormatFileId.HasValue ?
                new ObjectParameter("fldFormatFileId", fldFormatFileId) :
                new ObjectParameter("fldFormatFileId", typeof(int));
    
            var fldTypeParameter = fldType.HasValue ?
                new ObjectParameter("fldType", fldType) :
                new ObjectParameter("fldType", typeof(byte));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblLetterFileMojazUpdate", fldIdParameter, fldFormatFileIdParameter, fldTypeParameter, fldUserIdParameter, fldDescParameter, fldOrganIdParameter, fldIPParameter);
        }
    
        public virtual int spr_SignLetter(Nullable<long> fldId, Nullable<int> fldSigner, Nullable<int> fldUserID)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(long));
    
            var fldSignerParameter = fldSigner.HasValue ?
                new ObjectParameter("fldSigner", fldSigner) :
                new ObjectParameter("fldSigner", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_SignLetter", fldIdParameter, fldSignerParameter, fldUserIDParameter);
        }
    
        public virtual ObjectResult<spr_Charkhe> spr_Charkhe(Nullable<int> letterId, Nullable<int> chPid)
        {
            var letterIdParameter = letterId.HasValue ?
                new ObjectParameter("LetterId", letterId) :
                new ObjectParameter("LetterId", typeof(int));
    
            var chPidParameter = chPid.HasValue ?
                new ObjectParameter("ChPid", chPid) :
                new ObjectParameter("ChPid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_Charkhe>("spr_Charkhe", letterIdParameter, chPidParameter);
        }
    
        public virtual ObjectResult<spr_CharkheMessage> spr_CharkheMessage(Nullable<int> messageId, Nullable<int> chPid)
        {
            var messageIdParameter = messageId.HasValue ?
                new ObjectParameter("MessageId", messageId) :
                new ObjectParameter("MessageId", typeof(int));
    
            var chPidParameter = chPid.HasValue ?
                new ObjectParameter("ChPid", chPid) :
                new ObjectParameter("ChPid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_CharkheMessage>("spr_CharkheMessage", messageIdParameter, chPidParameter);
        }
    
        public virtual ObjectResult<spr_selectCountUnReadLetter> spr_selectCountUnReadLetter(Nullable<int> boxID, Nullable<int> comisionID, Nullable<int> organId)
        {
            var boxIDParameter = boxID.HasValue ?
                new ObjectParameter("BoxID", boxID) :
                new ObjectParameter("BoxID", typeof(int));
    
            var comisionIDParameter = comisionID.HasValue ?
                new ObjectParameter("ComisionID", comisionID) :
                new ObjectParameter("ComisionID", typeof(int));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_selectCountUnReadLetter>("spr_selectCountUnReadLetter", boxIDParameter, comisionIDParameter, organIdParameter);
        }
    
        public virtual ObjectResult<spr_SendToSecretariat> spr_SendToSecretariat(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SendToSecretariat>("spr_SendToSecretariat", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int spr_UpdateInternalAssignmentReceiver(Nullable<int> fldId, Nullable<int> statusID)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_UpdateInternalAssignmentReceiver", fldIdParameter, statusIDParameter);
        }
    
        public virtual ObjectResult<spr_tblMergeField_LetterTemplate_LetterIdSelect> spr_tblMergeField_LetterTemplate_LetterIdSelect(string value, string value2, Nullable<int> organId)
        {
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var value2Parameter = value2 != null ?
                new ObjectParameter("value2", value2) :
                new ObjectParameter("value2", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblMergeField_LetterTemplate_LetterIdSelect>("spr_tblMergeField_LetterTemplate_LetterIdSelect", valueParameter, value2Parameter, organIdParameter);
        }
    
        public virtual ObjectResult<spr_DeleteErjaatLetter> spr_DeleteErjaatLetter(Nullable<long> letterId, Nullable<int> fldUserId)
        {
            var letterIdParameter = letterId.HasValue ?
                new ObjectParameter("LetterId", letterId) :
                new ObjectParameter("LetterId", typeof(long));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_DeleteErjaatLetter>("spr_DeleteErjaatLetter", letterIdParameter, fldUserIdParameter);
        }
    
        public virtual ObjectResult<spr_SplitHtmlToEnglishWord> spr_SplitHtmlToEnglishWord(string hTMLText)
        {
            var hTMLTextParameter = hTMLText != null ?
                new ObjectParameter("HTMLText", hTMLText) :
                new ObjectParameter("HTMLText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SplitHtmlToEnglishWord>("spr_SplitHtmlToEnglishWord", hTMLTextParameter);
        }
    
        public virtual int spr_tblMergeFieldTypesDelete(Nullable<int> fldId, Nullable<int> fldUserId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblMergeFieldTypesDelete", fldIdParameter, fldUserIdParameter);
        }
    
        public virtual int spr_tblMergeFieldTypesInsert(string fldFaName, string fldEnName, Nullable<int> fldOrganId, Nullable<int> fldUserId, Nullable<bool> fldType)
        {
            var fldFaNameParameter = fldFaName != null ?
                new ObjectParameter("fldFaName", fldFaName) :
                new ObjectParameter("fldFaName", typeof(string));
    
            var fldEnNameParameter = fldEnName != null ?
                new ObjectParameter("fldEnName", fldEnName) :
                new ObjectParameter("fldEnName", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldTypeParameter = fldType.HasValue ?
                new ObjectParameter("fldType", fldType) :
                new ObjectParameter("fldType", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblMergeFieldTypesInsert", fldFaNameParameter, fldEnNameParameter, fldOrganIdParameter, fldUserIdParameter, fldTypeParameter);
        }
    
        public virtual ObjectResult<spr_tblMergeFieldTypesSelect> spr_tblMergeFieldTypesSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblMergeFieldTypesSelect>("spr_tblMergeFieldTypesSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblMergeFieldTypesUpdate(Nullable<int> fldId, string fldFaName, string fldEnName, Nullable<int> fldOrganId, Nullable<int> fldUserId, Nullable<bool> fldType)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldFaNameParameter = fldFaName != null ?
                new ObjectParameter("fldFaName", fldFaName) :
                new ObjectParameter("fldFaName", typeof(string));
    
            var fldEnNameParameter = fldEnName != null ?
                new ObjectParameter("fldEnName", fldEnName) :
                new ObjectParameter("fldEnName", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldTypeParameter = fldType.HasValue ?
                new ObjectParameter("fldType", fldType) :
                new ObjectParameter("fldType", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblMergeFieldTypesUpdate", fldIdParameter, fldFaNameParameter, fldEnNameParameter, fldOrganIdParameter, fldUserIdParameter, fldTypeParameter);
        }
    
        public virtual int spr_tblMergeField_LetterTemplateDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblMergeField_LetterTemplateDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblMergeField_LetterTemplateInsert(Nullable<int> fldLetterTamplateId, Nullable<int> fldMergeFieldId, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc, string fldIP)
        {
            var fldLetterTamplateIdParameter = fldLetterTamplateId.HasValue ?
                new ObjectParameter("fldLetterTamplateId", fldLetterTamplateId) :
                new ObjectParameter("fldLetterTamplateId", typeof(int));
    
            var fldMergeFieldIdParameter = fldMergeFieldId.HasValue ?
                new ObjectParameter("fldMergeFieldId", fldMergeFieldId) :
                new ObjectParameter("fldMergeFieldId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblMergeField_LetterTemplateInsert", fldLetterTamplateIdParameter, fldMergeFieldIdParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblMergeField_LetterTemplateSelect> spr_tblMergeField_LetterTemplateSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblMergeField_LetterTemplateSelect>("spr_tblMergeField_LetterTemplateSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblMergeField_LetterTemplateUpdate(Nullable<int> fldId, Nullable<int> fldLetterTamplateId, Nullable<int> fldMergeFieldId, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldLetterTamplateIdParameter = fldLetterTamplateId.HasValue ?
                new ObjectParameter("fldLetterTamplateId", fldLetterTamplateId) :
                new ObjectParameter("fldLetterTamplateId", typeof(int));
    
            var fldMergeFieldIdParameter = fldMergeFieldId.HasValue ?
                new ObjectParameter("fldMergeFieldId", fldMergeFieldId) :
                new ObjectParameter("fldMergeFieldId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblMergeField_LetterTemplateUpdate", fldIdParameter, fldLetterTamplateIdParameter, fldMergeFieldIdParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_tblLetter_MergeFieldTypeDelete(Nullable<long> fldLetterId, Nullable<int> fldUserID)
        {
            var fldLetterIdParameter = fldLetterId.HasValue ?
                new ObjectParameter("fldLetterId", fldLetterId) :
                new ObjectParameter("fldLetterId", typeof(long));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblLetter_MergeFieldTypeDelete", fldLetterIdParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblLetter_MergeFieldTypeInsert(Nullable<long> fldLetterId, Nullable<int> fldMergeTypeId, string fldValue, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc)
        {
            var fldLetterIdParameter = fldLetterId.HasValue ?
                new ObjectParameter("fldLetterId", fldLetterId) :
                new ObjectParameter("fldLetterId", typeof(long));
    
            var fldMergeTypeIdParameter = fldMergeTypeId.HasValue ?
                new ObjectParameter("fldMergeTypeId", fldMergeTypeId) :
                new ObjectParameter("fldMergeTypeId", typeof(int));
    
            var fldValueParameter = fldValue != null ?
                new ObjectParameter("fldValue", fldValue) :
                new ObjectParameter("fldValue", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblLetter_MergeFieldTypeInsert", fldLetterIdParameter, fldMergeTypeIdParameter, fldValueParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter);
        }
    
        public virtual int spr_tblLetter_MergeFieldTypeUpdate(Nullable<int> fldId, Nullable<long> fldLetterId, Nullable<int> fldMergeTypeId, string fldValue, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldLetterIdParameter = fldLetterId.HasValue ?
                new ObjectParameter("fldLetterId", fldLetterId) :
                new ObjectParameter("fldLetterId", typeof(long));
    
            var fldMergeTypeIdParameter = fldMergeTypeId.HasValue ?
                new ObjectParameter("fldMergeTypeId", fldMergeTypeId) :
                new ObjectParameter("fldMergeTypeId", typeof(int));
    
            var fldValueParameter = fldValue != null ?
                new ObjectParameter("fldValue", fldValue) :
                new ObjectParameter("fldValue", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblLetter_MergeFieldTypeUpdate", fldIdParameter, fldLetterIdParameter, fldMergeTypeIdParameter, fldValueParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblLetter_MergeFieldTypeSelect> spr_tblLetter_MergeFieldTypeSelect(string fieldname, string value, string value2, Nullable<int> organId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var value2Parameter = value2 != null ?
                new ObjectParameter("Value2", value2) :
                new ObjectParameter("Value2", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblLetter_MergeFieldTypeSelect>("spr_tblLetter_MergeFieldTypeSelect", fieldnameParameter, valueParameter, value2Parameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblAshkhaseHoghoghiTitlesDelete(Nullable<int> fldId, Nullable<int> fldUserId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblAshkhaseHoghoghiTitlesDelete", fldIdParameter, fldUserIdParameter);
        }
    
        public virtual int spr_tblAshkhaseHoghoghiTitlesInsert(string fldName, Nullable<int> fldAshkhasHoghoghiId, string fldIP, string fldDesc, Nullable<int> fldUserId, Nullable<int> fldOrganId)
        {
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var fldAshkhasHoghoghiIdParameter = fldAshkhasHoghoghiId.HasValue ?
                new ObjectParameter("fldAshkhasHoghoghiId", fldAshkhasHoghoghiId) :
                new ObjectParameter("fldAshkhasHoghoghiId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblAshkhaseHoghoghiTitlesInsert", fldNameParameter, fldAshkhasHoghoghiIdParameter, fldIPParameter, fldDescParameter, fldUserIdParameter, fldOrganIdParameter);
        }
    
        public virtual ObjectResult<spr_tblAshkhaseHoghoghiTitlesSelect> spr_tblAshkhaseHoghoghiTitlesSelect(string fieldname, string value, Nullable<int> organid, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var organidParameter = organid.HasValue ?
                new ObjectParameter("organid", organid) :
                new ObjectParameter("organid", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblAshkhaseHoghoghiTitlesSelect>("spr_tblAshkhaseHoghoghiTitlesSelect", fieldnameParameter, valueParameter, organidParameter, hParameter);
        }
    
        public virtual int spr_tblAshkhaseHoghoghiTitlesUpdate(Nullable<int> fldId, string fldName, Nullable<int> fldAshkhasHoghoghiId, string fldIP, string fldDesc, Nullable<int> fldUserId, Nullable<int> fldOrganId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var fldAshkhasHoghoghiIdParameter = fldAshkhasHoghoghiId.HasValue ?
                new ObjectParameter("fldAshkhasHoghoghiId", fldAshkhasHoghoghiId) :
                new ObjectParameter("fldAshkhasHoghoghiId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblAshkhaseHoghoghiTitlesUpdate", fldIdParameter, fldNameParameter, fldAshkhasHoghoghiIdParameter, fldIPParameter, fldDescParameter, fldUserIdParameter, fldOrganIdParameter);
        }
    
        public virtual ObjectResult<spr_tblLetterSelect> spr_tblLetterSelect(string fieldname, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblLetterSelect>("spr_tblLetterSelect", fieldnameParameter, valueParameter, organIdParameter, hParameter);
        }
    }
}
