//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RasaNewFMSEntities : DbContext
    {
        public RasaNewFMSEntities()
            : base("name=RasaNewFMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int spr_UpdateTarikhFishMotefareghe(Nullable<int> idfish, Nullable<System.DateTime> date, Nullable<int> flduserId)
        {
            var idfishParameter = idfish.HasValue ?
                new ObjectParameter("Idfish", idfish) :
                new ObjectParameter("Idfish", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var flduserIdParameter = flduserId.HasValue ?
                new ObjectParameter("flduserId", flduserId) :
                new ObjectParameter("flduserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_UpdateTarikhFishMotefareghe", idfishParameter, dateParameter, flduserIdParameter);
        }
    
        public virtual int spr_tblCheck_SmsDelete(Nullable<int> fldCheckId, Nullable<int> fldUserId)
        {
            var fldCheckIdParameter = fldCheckId.HasValue ?
                new ObjectParameter("fldCheckId", fldCheckId) :
                new ObjectParameter("fldCheckId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblCheck_SmsDelete", fldCheckIdParameter, fldUserIdParameter);
        }
    
        public virtual int spr_tblCheck_SmsInsert(Nullable<int> fldCheckId, Nullable<byte> fldStatus, Nullable<int> fldUserId, string fldIP)
        {
            var fldCheckIdParameter = fldCheckId.HasValue ?
                new ObjectParameter("fldCheckId", fldCheckId) :
                new ObjectParameter("fldCheckId", typeof(int));
    
            var fldStatusParameter = fldStatus.HasValue ?
                new ObjectParameter("fldStatus", fldStatus) :
                new ObjectParameter("fldStatus", typeof(byte));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblCheck_SmsInsert", fldCheckIdParameter, fldStatusParameter, fldUserIdParameter, fldIPParameter);
        }
    
        public virtual int spr_tblCheck_SmsUpdate(Nullable<int> fldId, Nullable<int> fldCheckId, Nullable<byte> fldStatus, Nullable<int> fldUserId, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldCheckIdParameter = fldCheckId.HasValue ?
                new ObjectParameter("fldCheckId", fldCheckId) :
                new ObjectParameter("fldCheckId", typeof(int));
    
            var fldStatusParameter = fldStatus.HasValue ?
                new ObjectParameter("fldStatus", fldStatus) :
                new ObjectParameter("fldStatus", typeof(byte));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblCheck_SmsUpdate", fldIdParameter, fldCheckIdParameter, fldStatusParameter, fldUserIdParameter, fldIPParameter);
        }
    }
}
