//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Models
{
    using System;
    
    public partial class spr_Charkhe
    {
        public Nullable<int> id { get; set; }
        public Nullable<int> sender { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> AssId { get; set; }
        public string SenderName { get; set; }
        public string fldTypeAss { get; set; }
        public string fldNameStatus { get; set; }
        public string fldLetterReadDate { get; set; }
        public string fldTarikhErja { get; set; }
        public string fldDesc { get; set; }
        public Nullable<int> C_SID { get; set; }
    }
}
