//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Models
{
    using System;
    
    public partial class spr_tblLetterActionsSelect
    {
        public int fldId { get; set; }
        public long fldLetterId { get; set; }
        public string fldTarikhAnjam { get; set; }
        public string fldTimeAnjam { get; set; }
        public int fldLetterActionTypeId { get; set; }
        public int fldUserId { get; set; }
        public int fldOrganId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIP { get; set; }
        public string fldSubject { get; set; }
        public string fldTitleActionType { get; set; }
    }
}
