//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Models
{
    using System;
    
    public partial class spr_SelectParamerValueFromArze
    {
        public int fldId { get; set; }
        public string fldNameParametreFa { get; set; }
        public string fldNameParametreEn { get; set; }
        public string fldvalue { get; set; }
        public Nullable<bool> fldFlag { get; set; }
        public int fldHeaderArzeId { get; set; }
        public int fldDetailIdArze { get; set; }
        public int fldNoeField { get; set; }
        public string fldValue_Combox { get; set; }
    }
}
