//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Models
{
    using System;
    
    public partial class spr_SendToSecretariat
    {
        public string fldStaffName { get; set; }
        public int SecretariatId { get; set; }
        public Nullable<int> PID { get; set; }
        public int CommisionId { get; set; }
    }
}
