//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Models
{
    using System;
    
    public partial class spr_tblReferralRulesSelectRecivers
    {
        public int fldid { get; set; }
        public string fldReceiverComisionName { get; set; }
        public int fldType { get; set; }
        public string fldId_Type { get; set; }
    }
}
