//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Models
{
    using System;
    
    public partial class spr_tblAshkhaseHoghoghiTitlesSelect
    {
        public int fldId { get; set; }
        public string fldName { get; set; }
        public int fldAshkhasHoghoghiId { get; set; }
        public string fldIP { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldUserId { get; set; }
        public int fldOrganId { get; set; }
        public string fldNameHoghoghi { get; set; }
    }
}
