//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WeightEntities : DbContext
    {
        public WeightEntities()
            : base("name=WeightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spr_SelectParamerValueFromArze> spr_SelectParamerValueFromArze(Nullable<int> shomarehesadCodeDarad, Nullable<int> baskoolId, Nullable<int> organId)
        {
            var shomarehesadCodeDaradParameter = shomarehesadCodeDarad.HasValue ?
                new ObjectParameter("shomarehesadCodeDarad", shomarehesadCodeDarad) :
                new ObjectParameter("shomarehesadCodeDarad", typeof(int));
    
            var baskoolIdParameter = baskoolId.HasValue ?
                new ObjectParameter("baskoolId", baskoolId) :
                new ObjectParameter("baskoolId", typeof(int));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectParamerValueFromArze>("spr_SelectParamerValueFromArze", shomarehesadCodeDaradParameter, baskoolIdParameter, organIdParameter);
        }
    
        public virtual int spr_DeleteFileHavale(Nullable<int> fldid, Nullable<int> fldUserId)
        {
            var fldidParameter = fldid.HasValue ?
                new ObjectParameter("fldid", fldid) :
                new ObjectParameter("fldid", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_DeleteFileHavale", fldidParameter, fldUserIdParameter);
        }
    
        public virtual ObjectResult<spr_SelectIsEbtalFishDaramd> spr_SelectIsEbtalFishDaramd(Nullable<int> idvazn, Nullable<int> fldOrganId, Nullable<int> fldModuleId)
        {
            var idvaznParameter = idvazn.HasValue ?
                new ObjectParameter("idvazn", idvazn) :
                new ObjectParameter("idvazn", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldModuleIdParameter = fldModuleId.HasValue ?
                new ObjectParameter("fldModuleId", fldModuleId) :
                new ObjectParameter("fldModuleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectIsEbtalFishDaramd>("spr_SelectIsEbtalFishDaramd", idvaznParameter, fldOrganIdParameter, fldModuleIdParameter);
        }
    }
}
