//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NewFMS.Bime {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BimeSRVSoap", Namespace="http://tempuri.org/")]
    public partial class BimeSRV : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetBimeInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCityCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRasteCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateDiscBazneshastegiOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BimeSRV() {
            this.Url = global::NewFMS.Properties.Settings.Default.NewFMS_Bime_BimeSRV;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetBimeInfoCompletedEventHandler GetBimeInfoCompleted;
        
        /// <remarks/>
        public event GetCityCodeCompletedEventHandler GetCityCodeCompleted;
        
        /// <remarks/>
        public event GetRasteCodeCompletedEventHandler GetRasteCodeCompleted;
        
        /// <remarks/>
        public event GenerateDiscBazneshastegiCompletedEventHandler GenerateDiscBazneshastegiCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBimeInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Bime[] GetBimeInfo(string FieldName, short Year, byte Month, byte NobatePardakht, int OrganId, string Sh_List) {
            object[] results = this.Invoke("GetBimeInfo", new object[] {
                        FieldName,
                        Year,
                        Month,
                        NobatePardakht,
                        OrganId,
                        Sh_List});
            return ((Bime[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBimeInfoAsync(string FieldName, short Year, byte Month, byte NobatePardakht, int OrganId, string Sh_List) {
            this.GetBimeInfoAsync(FieldName, Year, Month, NobatePardakht, OrganId, Sh_List, null);
        }
        
        /// <remarks/>
        public void GetBimeInfoAsync(string FieldName, short Year, byte Month, byte NobatePardakht, int OrganId, string Sh_List, object userState) {
            if ((this.GetBimeInfoOperationCompleted == null)) {
                this.GetBimeInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBimeInfoOperationCompleted);
            }
            this.InvokeAsync("GetBimeInfo", new object[] {
                        FieldName,
                        Year,
                        Month,
                        NobatePardakht,
                        OrganId,
                        Sh_List}, this.GetBimeInfoOperationCompleted, userState);
        }
        
        private void OnGetBimeInfoOperationCompleted(object arg) {
            if ((this.GetBimeInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBimeInfoCompleted(this, new GetBimeInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCityCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetCityCode(string CityName) {
            object[] results = this.Invoke("GetCityCode", new object[] {
                        CityName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetCityCodeAsync(string CityName) {
            this.GetCityCodeAsync(CityName, null);
        }
        
        /// <remarks/>
        public void GetCityCodeAsync(string CityName, object userState) {
            if ((this.GetCityCodeOperationCompleted == null)) {
                this.GetCityCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCityCodeOperationCompleted);
            }
            this.InvokeAsync("GetCityCode", new object[] {
                        CityName}, this.GetCityCodeOperationCompleted, userState);
        }
        
        private void OnGetCityCodeOperationCompleted(object arg) {
            if ((this.GetCityCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCityCodeCompleted(this, new GetCityCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRasteCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetRasteCode(string RasteName) {
            object[] results = this.Invoke("GetRasteCode", new object[] {
                        RasteName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetRasteCodeAsync(string RasteName) {
            this.GetRasteCodeAsync(RasteName, null);
        }
        
        /// <remarks/>
        public void GetRasteCodeAsync(string RasteName, object userState) {
            if ((this.GetRasteCodeOperationCompleted == null)) {
                this.GetRasteCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRasteCodeOperationCompleted);
            }
            this.InvokeAsync("GetRasteCode", new object[] {
                        RasteName}, this.GetRasteCodeOperationCompleted, userState);
        }
        
        private void OnGetRasteCodeOperationCompleted(object arg) {
            if ((this.GetRasteCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRasteCodeCompleted(this, new GetRasteCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerateDiscBazneshastegi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerateDiscBazneshastegi(string WorkerMasir, int OrganId, string Sh_Fish, string DateVariz, short Year, byte Month, byte NobatePardakht) {
            object[] results = this.Invoke("GenerateDiscBazneshastegi", new object[] {
                        WorkerMasir,
                        OrganId,
                        Sh_Fish,
                        DateVariz,
                        Year,
                        Month,
                        NobatePardakht});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateDiscBazneshastegiAsync(string WorkerMasir, int OrganId, string Sh_Fish, string DateVariz, short Year, byte Month, byte NobatePardakht) {
            this.GenerateDiscBazneshastegiAsync(WorkerMasir, OrganId, Sh_Fish, DateVariz, Year, Month, NobatePardakht, null);
        }
        
        /// <remarks/>
        public void GenerateDiscBazneshastegiAsync(string WorkerMasir, int OrganId, string Sh_Fish, string DateVariz, short Year, byte Month, byte NobatePardakht, object userState) {
            if ((this.GenerateDiscBazneshastegiOperationCompleted == null)) {
                this.GenerateDiscBazneshastegiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateDiscBazneshastegiOperationCompleted);
            }
            this.InvokeAsync("GenerateDiscBazneshastegi", new object[] {
                        WorkerMasir,
                        OrganId,
                        Sh_Fish,
                        DateVariz,
                        Year,
                        Month,
                        NobatePardakht}, this.GenerateDiscBazneshastegiOperationCompleted, userState);
        }
        
        private void OnGenerateDiscBazneshastegiOperationCompleted(object arg) {
            if ((this.GenerateDiscBazneshastegiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateDiscBazneshastegiCompleted(this, new GenerateDiscBazneshastegiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bime {
        
        private int tedadMardField;
        
        private int tedadZanField;
        
        private decimal j_MazayaField;
        
        private decimal j_motalebatField;
        
        private decimal j_Bime_PField;
        
        private decimal j_Bime_KField;
        
        private decimal j_bime_bikariField;
        
        private string masir_KARField;
        
        private string masir_WORField;
        
        private int kargahIdField;
        
        private int salField;
        
        private int mahField;
        
        /// <remarks/>
        public int TedadMard {
            get {
                return this.tedadMardField;
            }
            set {
                this.tedadMardField = value;
            }
        }
        
        /// <remarks/>
        public int TedadZan {
            get {
                return this.tedadZanField;
            }
            set {
                this.tedadZanField = value;
            }
        }
        
        /// <remarks/>
        public decimal J_Mazaya {
            get {
                return this.j_MazayaField;
            }
            set {
                this.j_MazayaField = value;
            }
        }
        
        /// <remarks/>
        public decimal j_motalebat {
            get {
                return this.j_motalebatField;
            }
            set {
                this.j_motalebatField = value;
            }
        }
        
        /// <remarks/>
        public decimal J_Bime_P {
            get {
                return this.j_Bime_PField;
            }
            set {
                this.j_Bime_PField = value;
            }
        }
        
        /// <remarks/>
        public decimal J_Bime_K {
            get {
                return this.j_Bime_KField;
            }
            set {
                this.j_Bime_KField = value;
            }
        }
        
        /// <remarks/>
        public decimal j_bime_bikari {
            get {
                return this.j_bime_bikariField;
            }
            set {
                this.j_bime_bikariField = value;
            }
        }
        
        /// <remarks/>
        public string Masir_KAR {
            get {
                return this.masir_KARField;
            }
            set {
                this.masir_KARField = value;
            }
        }
        
        /// <remarks/>
        public string Masir_WOR {
            get {
                return this.masir_WORField;
            }
            set {
                this.masir_WORField = value;
            }
        }
        
        /// <remarks/>
        public int KargahId {
            get {
                return this.kargahIdField;
            }
            set {
                this.kargahIdField = value;
            }
        }
        
        /// <remarks/>
        public int sal {
            get {
                return this.salField;
            }
            set {
                this.salField = value;
            }
        }
        
        /// <remarks/>
        public int mah {
            get {
                return this.mahField;
            }
            set {
                this.mahField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetBimeInfoCompletedEventHandler(object sender, GetBimeInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBimeInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBimeInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Bime[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Bime[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetCityCodeCompletedEventHandler(object sender, GetCityCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCityCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCityCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetRasteCodeCompletedEventHandler(object sender, GetRasteCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRasteCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRasteCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GenerateDiscBazneshastegiCompletedEventHandler(object sender, GenerateDiscBazneshastegiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateDiscBazneshastegiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateDiscBazneshastegiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591