// Copyright 2014-2018 VintaSoft Ltd. All rights reserved.
// This software is protected by International copyright laws.
// Any copying, duplication, deployment, redistribution, modification or other
// disposition hereof is STRICTLY PROHIBITED without an express written license
// granted by VintaSoft Ltd. This notice may not be removed or otherwise
// altered under any circumstances.
// This code may NOT be used apart of the VintaSoft product.
var Vintasoft;
(function(v){if(void 0==window.jQuery)throw Error("jQuery is not found.");if(void 0==v.version)v.version="1.0.10.1";else if("1.0.10.1"!==v.version)throw Error("Wrong script version.");v.Shared=v.Shared||(v.Shared={});(function(l){function v(a){function b(){}b.prototype=a;return new b}Array.isArray||(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var k;if(null==this)throw new TypeError('"this" is null or not defined');var g=
Object(this),d=g.length>>>0;if(0===d)return-1;k=+b||0;Infinity===Math.abs(k)&&(k=0);if(k>=d)return-1;for(k=Math.max(0<=k?k:d-Math.abs(k),0);k<d;){if(k in g&&g[k]===a)return k;k++}return-1});l.extend=function(a,b){a.prototype=v(b.prototype);a.prototype.constructor=a;a.superclass=b.prototype};var b=function(){};b.te=function(a){throw Error(a);};b.tae=function(){b.te("Argument type exception.")};b.toe=function(){b.te("Argument out of range exception.")};b.n=function(){for(var a=0;a<arguments.length;a++){var f=
arguments[a];("number"!==typeof f||isNaN(f))&&b.tae()}};b.b=function(){for(var a=0;a<arguments.length;a++)"boolean"!==typeof arguments[a]&&b.tae()};b.d=function(a){a instanceof Date||(a=Date.parse(a),isNaN(a)&&b.tae(),a=new Date(a));return a};b.s=function(){for(var a=0;a<arguments.length;a++)"string"!==typeof arguments[a]&&b.tae()};b.sz=function(){for(var a=0;a<arguments.length;a++){var f=arguments[a];b.n(f.width);b.n(f.height)}};b.p=function(){for(var a=0;a<arguments.length;a++){var f=arguments[a];
b.n(f.x);b.n(f.y)}};b.r=function(){for(var a=0;a<arguments.length;a++){var f=arguments[a];b.p(f);b.sz(f)}};b.e=function(a,b){return new b(a instanceof A?a.valueOf():a)};b.c=function(a,f,k){a instanceof f||(void 0!=k?b.te(k):b.tae())};b.ad=function(a,f){Array.isArray(a)||b.tae();for(var k=0;k<a.length;k++)f(a[k])};b.ac=function(a,f){b.ad(a,function(a){b.c(a,f)})};var A=function(){var a=A.prototype;a.getAllAvailableNames=function(){};a.getAllAvailableValues=function(){};a.valueOf=function(){};a.toString=
function(){};a.equals=function(a){};a.isFlagged=function(){return!1}},C=function(){var a=C.prototype;a.toArray=function(){};a.contains=function(a){};a.add=function(a){};a.remove=function(a){};a.isFlagged=function(){return!0}};l.extend(C,A);var z=function(){};z.create=function(a,f){function k(a,h){var b=[];if(void 0!=e[h])b.push(e[h]);else for(var u=1;u<=c;)0!==d(h,u)&&b.push(e[u]),u*=2;return b.join("|")}function g(c){return{low:c%4294967296|0,high:c/4294967296|0}}function d(c,d){var a=g(c),h=g(d);
return 4294967296*(a.high&h.high)+((a.low&h.low)>>>0)}for(var e={},c=0,h=0;h<a.length;h++){var m=a[h].value,G=a[h].name;e[G]=m;e[m]=G}Object.freeze&&Object.freeze(e);if(f)for(h in e)isNaN(Number(h))||(m=parseInt(h),0!==m&&0===d(m,m-1)&&(c+=m));else for(h in e)isNaN(Number(h))||(m=parseInt(h),m>c&&(c=m));var u=function(d){"string"===typeof d&&(d=e[d]);d>c&&b.tae();var a=e[d];void 0==a&&f&&(a=k(this,d));void 0!=a&&""!==a||b.tae();this[this[a]=d+0]=a};f?l.extend(u,C):l.extend(u,A);h=u.prototype;h.getAllAvailableNames=
function(){var d=[],c;for(c in e)isNaN(Number(c))&&d.push(c);return d};h.getAllAvailableValues=function(){var d=[],c;for(c in e)isNaN(Number(c))&&void 0!=e[c]&&d.push(e[c]);return d};h.valueOf=function(){for(var d in this){var c=Number(d);if(!isNaN(c))return c}};h.toString=function(){return k(this,this.valueOf())};f&&(h.toArray=function(){var a=this.valueOf(),h=[];if(0===a&&void 0!==e[a])h.push(new u(0));else for(var b=1;b<=c;){if(0!==d(a,b))try{h.push(new u(b))}catch(G){}b*=2}return h},h.contains=
function(c){var a=this.valueOf();"string"===typeof c&&(c=e[c]);return d(a,c)===c+0},h.add=function(c){var d=this.valueOf();"string"===typeof c&&(c=e[c]);d=g(d);c=g(c);return new u(4294967296*(d.high|c.high)+((d.low|c.low)>>>0))},h.remove=function(c){var a=this.valueOf();"string"===typeof c&&(c=e[c]);var h=c;c=g(a);h=g(h);return new u(d(4294967296*(c.high^h.high)+((c.low^h.low)>>>0),a))});h.equals=function(c){var d=this.valueOf();"string"===typeof c&&(c=e[c]);return d===c+0};h.isFlagged=function(){return f};
return u};l.WebPixelFormatEnumJS=z.create([{name:"Undefined",value:0},{name:"Indexed1",value:1},{name:"BlackWhite",value:2},{name:"Indexed4",value:4},{name:"Indexed8",value:8},{name:"Gray8",value:9},{name:"Bgr555",value:14},{name:"Bgr565",value:15},{name:"Gray16",value:16},{name:"Bgr24",value:24},{name:"Bgr32",value:32},{name:"Bgra32",value:33},{name:"Bgr48",value:48},{name:"Bgra64",value:64}],!1);l.WebInterpolationModeEnumJS=z.create([{name:"Default",value:0},{name:"Low",value:1},{name:"High",value:2},
{name:"Bilinear",value:3},{name:"Bicubic",value:4},{name:"NearestNeighbor",value:5},{name:"HighQualityBilinear",value:6},{name:"HighQualityBicubic",value:7}],!1);l.WebSmoothingModeEnumJS=z.create([{name:"Default",value:0},{name:"HighSpeed",value:1},{name:"HighQuality",value:2},{name:"None",value:3},{name:"AntiAlias",value:4}],!1);l.WebImageTypeEnumJS=z.create([{name:"Url",value:1},{name:"Base64",value:2}],!1);l.WebImagingEnviromentJS=function(){};l.WebImagingEnviromentJS._57=function(){};l.WebImagingEnviromentJS._57=
void 0;l.WebImagingEnviromentJS.get_SessionId=function(){return l.WebImagingEnviromentJS._57};l.WebImagingEnviromentJS.set_SessionId=function(a){void 0!=l.WebImagingEnviromentJS._57&&b.te("Session ID already initialized.");/^\w+$/.test(a)||b.te("Unsupported Session ID format: ID can contain only latin letters, numbers and '_' symbol.");l.WebImagingEnviromentJS._57=a};l.WebImagingEnviromentJS.get_ScrollSize=function(){var a=document.createElement("div");a.id="FindScrollSizeDiv";a.style.overflow="scroll";
a.style.visibility="hidden";a.style.position="absolute";a.style.width="100px";a.style.height="100px";document.body.appendChild(a);var b=a.offsetWidth-a.clientWidth;0>b&&(b=100-a.clientWidth);$("#FindScrollSizeDiv").remove();return b};l.WebImagingEnviromentJS.getScreenDpi=function(){var a=$("<div>",{id:"FindDpiDiv"}).appendTo(document.getElementsByTagName("body")[0]);$(a).css("position","absolute");$(a).css("top","-100%");$(a).css("left","-100%");$(a).css("width","1in");$(a).css("height","1in");a=
document.getElementById("FindDpiDiv");a={dpiX:a.offsetWidth,dpiY:a.offsetHeight};$("#FindDpiDiv").remove();return a};l.WebImagingEnviromentJS.guid=function(){function a(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()};var y=function(a,b,k,g,d){var e=y.prototype;e.get_ShortName=function(){return this._144};e.get_FullName=function(){return this._48};e.get_Value=function(){return this._193};e.get_ReadOnly=function(){return this._82};
e.get_Items=function(){return this._68};e.get_RefreshFromParent=function(){return this._140};this._144=a;this._48=b;this._193=k;this._82=g;this._68=[];this._140=d?d:!1},H=function(a,b,k){function g(c,d){c._193=d._193;c._48=d._48;c._144=d._144;c._82=d._82;c._140=d._140;for(var a=0;a<c._68.length;a++)g(c._68[a],d._68[a])}function d(c,a){for(;c._68.length>a._68.length;)c._68.splice(c._68.length-1,1);for(;c._68.length<a._68.length;)c._68[c._68.length]=a._68[c._68.length];for(var h=0;h<c._68.length;h++)d(c._68[h],
a._68[h])}function e(c,d,a){if(c["set_"+d])return c["set_"+d](a),c["get_"+d]();c[d]=a;return c[d]}function c(d,a,h){if("object"===typeof a){var e=[],b;for(b in a)e.push(b);e.sort();for(b=0;b<e.length;b++){var g=e[b],m="";if(0===g.lastIndexOf("get_",0)&&"function"===typeof a[g]){var m=g.split("_")[1],k=!0;void 0!=a["set_"+m]&&"function"===typeof a["set_"+m]&&(k=!1);var f;try{f=a[g]()}catch(l){f=void 0}if(void 0!=f)if("object"!=typeof f){var n=""!==h?h+"_"+m:m,m=new y(m,n,f,k);d.get_Items().push(m)}else n=
""!==h?h+"_"+m:m,m=new y(m,n,f,k),d.get_Items().push(m),c(m,f,n)}}if(0===d._68.length&&"object"===typeof a){b=!0;for(g in a)if("function"===typeof a[g]){b=!1;break}g=Object.getOwnPropertyNames(a);f=Array.isArray(a);if(b&&!f)for(b=0;b<g.length;b++)"_"!==g[b][0]&&(n=""!==h?h+"_"+g[b]:g[b],f=a[g[b]],void 0!=f&&("object"!=typeof f?(m=new y(g[b],n,f,!1,!0),d.get_Items().push(m)):(m=new y(g[b],n,f,!1,!0),d.get_Items().push(m),c(m,f,n))));else if(f)for(h=d.get_FullName(),k=!1,b=0;b<a.length;b++)m=new y(""+
b,h+"_"+b,a[b],k,!0),d.get_Items().push(m),c(m,a[b],h+"_"+b)}}}function h(c,d,a,b){var e=d.get_Items();if(e.length!==b._68.length)a.push({property:b,value:d._193,updateMarkup:!0});else{for(var m=!1,g=0;g<e.length;g++){d=e[g];var f=b._68[g];if(d._48!==f._48){a.push({property:b,value:d._193,updateMarkup:!0});m=!0;break}}if(!m)for(g=0;g<e.length;g++)if(d=e[g],f=b._68[g],d._48!==f._48)a.push({property:f,value:f._193,updateMarkup:!0});else if(f._68.length!==d._68.length)a.push({property:f,value:f._193,
updateMarkup:!0});else if(0!=d._68.length)h(c,d,a,f);else if(m=f._193,d._193!=m){f=!0;if(d._193 instanceof Array&&m instanceof Array)if(d._193.length!=m.length)f=!1;else for(var k=0;k<d._193.length;k++){if(d._193[k]!=m[k]){f=!1;break}}else f=!1;f||a.push({property:d,value:m})}}}var m=H.prototype;m.get_ObjectProperties=function(){return this._332};m.setPropertyValue=function(c,d){for(var a=this._60,b=c.split("_"),h=this._332,m=-1,g=0;g<b.length;g++)for(var f=0;f<h._68.length;f++)if(h._68[f]._144===
b[g]){h=h._68[f];-1==m||h._140||(m=-1);-1==m&&h._140&&(m=Math.max(g-1,0));break}var k;if(void 0!=h){f=[];switch(typeof h._193){case "boolean":d="True"===d?!0:!1;break;case "number":d=parseFloat(d)}try{if(1==b.length){var l=b[0];e(a,l,d)}else if(h._140){p=a;for(a=0;a<m;a++)p=Array.isArray(p)&&!isNaN(Number(b[a]))?p[Number(b[a])]:p["get_"+b[a]]();for(var n=b[m],q=p["get_"+n](),a=q,g=m+1;g<b.length-1;g++)a=isNaN(Number(b[g]))?a["get_"+b[g]]():a[Number(b[g])];l=b[b.length-1];a[l]=d;e(p,n,q)}else{for(var p=
a,g=0;g<b.length-1;g++)p=Array.isArray(p)&&!isNaN(Number(b[g]))?p[Number(b[g])]:p["get_"+b[g]]();l=b[b.length-1];e(p,l,d)}f=this.updatePropertyGrid(new H(this._60))}catch(s){f.push(h),k=s}0===f.length&&h._193!==d&&f.push(h);return{changedProperties:f,exception:k}}};m.updatePropertyGrid=function(c){var a=[],b=[];h(this,this._332,a,c._332);if(0!=a.length)for(var e=0;e<a.length;e++)a[e].property._193=a[e].value,b.push(a[e].property);d(this._332,c._332);g(this._332,c._332);return b};this._60=a;void 0==
b&&(b="");void 0==k&&(k="");this._332=new y(b,k,a,!1);c(this._332,a,k)},s=function(a,f,k,g){function d(c,d,a){if("string"===typeof c)try{c=JSON.parse(c)}catch(b){}k&&("error"===d&&void 0==c.errorMessage&&""===c.responseText&&(c.errorMessage="Unknown service error OR service is unavailable."),k(c,d,a))}var e=s.prototype;e.get_ActionName=function(){return this._83};e._27=function(){var c=$.extend(!0,{},this._216);c.success=this._37;c.error=this._300;return c};""===a&&b.te("Action name can not be empty.");
void 0!=f&&"function"!==typeof f&&b.te("Success callback must be defined as function.");void 0!=k&&"function"!==typeof k&&b.te("Error callback must be defined as function.");this._83=a;this._300=d;this._37=function(c,a,b){if("string"===typeof c)try{c=JSON.parse(c)}catch(e){}c.success?f&&f(c,a,b):d(c,a,b)};this._216=g},D=function(a,f){var k=D.prototype;k.compositeError=function(a){};k.compositeSuccess=function(a){};k._27=function(){if(0!=this._62.length){for(var a=this._62[0]._27(),d=[],b=0;b<this._62.length;b++)d[b]=
this._62[b]._216.data,d[b].requestId=b;var c=this;a.data={requestsData:d};a.success=function(a,d,b){if("string"===typeof a)try{a=JSON.parse(a)}catch(e){}for(d=0;d<a.length;d++)b=parseInt(a[d].requestId),b=c._62[b],void 0!=b._37&&b._37(a[d]);$(c).triggerHandler("compositeSuccess")};a.error=function(a,d,b){if("string"===typeof a)try{a=JSON.parse(a)}catch(e){}if("object"===typeof a&&a.length)for(d=0;d<a.length;d++)b=parseInt(a[d].requestId),b=c._62[b],void 0!=b._300&&b._300(a[d]);else for("error"===
d&&void 0==a.errorMessage&&""===a.responseText&&(a.errorMessage="Unknown service error OR service is unavailable."),d=0;d<c._62.length;d++)b=c._62[d],void 0!=b._300&&b._300(a);$(c).triggerHandler("compositeError")};return a}};this._83=f;b.ac(a,s);this._62=a;delete k.compositeError;delete k.compositeSuccess};l.extend(D,s);var q=function(a){var f=q.prototype;f.get_ServiceRoute=function(){return this._63};f.addRequest=function(a){b.c(a,s);if(0===this._109)return this.sendRequest(a);this._317.push(a)};
f.sendRequests=function(){var a=[],b=this._122();if(0!=b.length)for(var d=0;d<b.length;d++)a.push(this.sendRequest(b[d]));for(d=0;d<this._317.length;d++)a.push(this.sendRequest(this._317[d]));this._317=[];return a};f.sendRequest=function(a){b.te("Not implemented exception.")};f.__beginInit=function(){this._109++};f.__endInit=function(){this._109--;0>this._109&&(this._109=0);if(0===this._109)return this.sendRequests()};f._122=function(){for(var a=[],b=0;b<this._317.length;){var d=this._317[b]._83,
e=q.__registeredCompositeRequests[d];if(void 0!=e){for(var c=b,h=[];c<this._317.length;)this._317[c]._83===d?(h.push(this._317[c]),this._317.splice(c,1)):c++;a.push(new D(h,e))}else b++}return a};this._63=a;this._109=0;this._317=[]};q.defaultUrlImageService=-1;q.defaultImageService=-1;q.__registeredCompositeRequests={};q._280=function(a,f){b.s(a,f);""!==a&&""!==f||b.tae();void 0!=q.__registeredCompositeRequests[a]&&b.tae();q.__registeredCompositeRequests[a]=f};q._280("RenderThumbnail","RenderThumbnails");
q._280("GetImageInfo","GetImagesInfo");var E=function(a){E.superclass.constructor.apply(this,arguments);E.prototype.sendRequest=function(a){var b=a._27();b.data instanceof FormData?b.data.append("sessionId",l.WebImagingEnviromentJS._57):(void 0!=b.data?("object"===typeof b.data&&(b.data.sessionId=l.WebImagingEnviromentJS._57),b.data=JSON.stringify(b.data)):b.data=JSON.stringify(l.WebImagingEnviromentJS._57),b.contentType="application/json");b.url=this._63+"/"+a._83;return{request:a,object:$.ajax(b)}}};
l.extend(E,q);var F=function(a){F.superclass.constructor.apply(this,arguments);F.prototype.sendRequest=function(a){var b=a._27();b.url=this._63;var g=b.data;g instanceof FormData?(g.append("action",a._83),g.append("sessionId",l.WebImagingEnviromentJS._57)):(void 0==g&&(g=l.WebImagingEnviromentJS._57),"object"===typeof g?(g.sessionId=l.WebImagingEnviromentJS._57,g={requestParams:JSON.stringify(g),action:a._83}):g={requestParams:g,action:a._83});b.data=g;return{request:a,object:$.ajax(b)}}};l.extend(F,
q);var t=function(a,f,k){var g=t.prototype;g.changed=function(a){};g.get_Resolution=function(){return{x:this._168.x,y:this._168.y}};g.set_Resolution=function(a,e){var c;c=void 0==e?{x:a.x,y:a.y}:{x:a,y:e};b.p(c);var h=this._168;if(h.x!==c.x||h.y!==c.y)this._168=c,this._73||$(this).triggerHandler("changed")};g.get_InterpolationMode=function(){return this._247};g.set_InterpolationMode=function(a){a=b.e(a,l.WebInterpolationModeEnumJS);a.equals(this._247)||(this._247=a,this._73||$(this).triggerHandler("changed"))};
g.get_SmoothingMode=function(){return this._23};g.set_SmoothingMode=function(a){a=b.e(a,l.WebSmoothingModeEnumJS);a.equals(this._23)||(this._23=a,this._73||$(this).triggerHandler("changed"))};g.clone=function(){return new this.constructor(this._168,this._247,this._23)};g.equals=function(a){return a instanceof t?this._168.x===a._168.x&&this._168.y===a._168.y&&this._247.valueOf()===a._247.valueOf()&&this._23.valueOf()===a._23.valueOf():!1};g.isEmpty=function(){return this.equals(new t)};g.beginInit=
function(){this._73||(this._73=!0,this._192=this.clone())};g.endInit=function(){this._73&&(this._73=!1,void 0==this._192||this.equals(this._192)||(this._192=void 0,$(this).triggerHandler("changed")))};g._97=function(){return{resolution:this._168,interpolationMode:this._247.valueOf(),smoothingMode:this._23.valueOf()}};void 0==a&&(a={x:0,y:0});b.p(a);this._168={x:a.x,y:a.y};void 0==f&&(f=6);this._247=b.e(f,l.WebInterpolationModeEnumJS);void 0==k&&(k=4);this._23=b.e(k,l.WebSmoothingModeEnumJS);this._73=
!1;this._192=void 0;delete g.changed},x=function(){var a=x.prototype;a.changed=function(a){};a.get_IsColorManagementEnabled=function(){return this._93};a.set_IsColorManagementEnabled=function(a){b.b(a);this._93!==a&&(this._93=a,$(this).triggerHandler("changed"))};a.clone=function(){var a=new this.constructor;a._93=this._93;return a};a.equals=function(a){return a instanceof x?this._93===a._93:!1};a._97=function(){return{isColorManagementEnabled:this._93}};this._93=!0;delete a.changed},B=function(a,
f,k){this._15=a;void 0==f&&(f=-1!==q.defaultImageService?q.defaultImageService:q.defaultUrlImageService);-1!==f&&b.c(f,q,"You should specify correct image service OR define the default image service.");this._101=f;void 0==k&&(k=q.defaultAnnotationService);void 0!=k&&(b.c(k,q,"You should specify correct annotation service OR define the default annotation service"),this._202=k);a=B.prototype;a.get_ImageId=function(){return this._15};a.get_ImageService=function(){b.c(this._101,q,"Image service is not an instance of WebServiceJS class.");
return this._101};a.get_AnnotationService=function(){b.c(this._202,q,"Image annotating service is not an instance of WebServiceJS class.");return this._202};a.equals=function(a){return this===a?!0:a instanceof B&&this._15===a._15?this._101._63===a._101._63&&(void 0==this._202&&void 0==a._202||void 0!=this._202&&void 0!=a._202&&this._202._63===a._202._63):!1};a._58=function(a,d,e,c,h){b.n(a);void 0!=d&&b.c(d,t);void 0!=e&&b.c(e,x);var m={};m.imageInfo={imageId:this._15,pageIndex:a};void 0==d||d.isEmpty()||
(m.renderingSettings=d._97());void 0!=e&&(m.decodingSettings=e._97());a=new s("GetImageInfo",c,h,{type:"POST",data:m});return this._101.addRequest(a)};a._16=function(a,d,e,c,h,m,f,k,n){h=b.e(h,l.WebImageTypeEnumJS);b.n(a,d,e);b.b(c);void 0!=m&&b.c(m,t);void 0!=f&&b.c(f,x);var r={};r.imageInfo={imageId:this._15,pageIndex:a};r.thumbnailSize={width:d,height:e};r.imageType=h.valueOf();r.useCache=c;r.applicationUrl=window.location.href;void 0==m||m.isEmpty()||(r.renderingSettings=m._97());void 0!=f&&(r.decodingSettings=
f._97());a=new s("RenderThumbnail",k,n,{type:"POST",data:r});this._101.addRequest(a)};a._350=function(a,d,e,c,h,m,f,k,n,r,p,q){k=b.e(k,l.WebImageTypeEnumJS);b.n(a,d,e,c,h);b.b(f);b.p(m);void 0!=n&&b.c(n,t);void 0!=r&&b.c(r,x);var w={};w.imageInfo={imageId:this._15,pageIndex:a};w.tileSize={width:c,height:h};w.imagePoint={x:d,y:e};w.scale=m;w.useCache=f;w.applicationUrl=window.location.href;w.imageType=k.valueOf();void 0==n||n.isEmpty()||(w.renderingSettings=n._97());void 0!=r&&(w.decodingSettings=
r._97());a=new s("GetImageTile",p,q,{type:"POST",data:w});return this._101.sendRequest(a)};a._177=function(a,d,e,c,h,m,f,k,n){h=b.e(h,l.WebImageTypeEnumJS);b.n(a,d,e);b.p(c);void 0!=m&&b.c(m,t);void 0!=f&&b.c(f,x);var r={};r.imageInfo={imageId:this._15,pageIndex:a};r.tileSize={width:d,height:e};r.scale=c;r.applicationUrl=window.location.href;r.imageType=h.valueOf();void 0==m||m.isEmpty()||(r.renderingSettings=m._97());void 0!=f&&(r.decodingSettings=f._97());a=new s("RenderImageTiles",k,n,{type:"POST",
data:r});return this._101.sendRequest(a)};a._45=function(a,d,e,c,h){b.n(a);void 0!=d&&b.c(d,t);void 0!=e&&b.c(e,x);var m={};m.imageInfo={imageId:this._15,pageIndex:a};m.applicationUrl=window.location.href;void 0==d||d.isEmpty()||(m.renderingSettings=d._97());void 0!=e&&(m.decodingSettings=e._97());a=new s("GetImageAsBase64String",c,h,{type:"POST",data:m});return this._101.sendRequest(a)}},n=function(a,f){function k(a){$(a._8).on("changed."+a._229,function(){g(a)})}function g(a){!1!==a._296&&a._change_IDG();
$(a).triggerHandler("renderingSettingsChanged")}function d(a){if(void 0!=a._30)$(a._30).on("changed."+a._229,function(){e(a)})}function e(a,d){d&&a._change_IDG();$(a).triggerHandler("decodingSettingsChanged")}n.prototype.renderingSettingsChanged=function(a){};n.prototype.decodingSettingsChanged=function(a){};n.prototype.idg_changed=function(a){};n.prototype.get_ImageId=function(){return this._356._15};n.prototype.get_Size=function(){return void 0==this._0||void 0==this._277?void 0:{width:this._0,
height:this._277}};n.prototype.get_Resolution=function(){return void 0==this._212||void 0==this._343?void 0:{x:this._212,y:this._343}};n.prototype.get_PixelFormat=function(){return this._307};n.prototype.get_Source=function(){return this._356};n.prototype.get_PageIndex=function(){return this._221};n.prototype.get_IsVector=function(){return this._296};n.prototype.get_RenderingSettings=function(){return this._8};n.prototype.set_RenderingSettings=function(a){b.c(a,t);this._8.equals(a)||($(this._8).off("."+
this._229),this._8=a,k(this),g(this))};n.prototype.get_DecodingSettings=function(){return this._30};n.prototype.set_DecodingSettings=function(a){void 0!=a&&b.c(a,x);if(!(void 0!=this._30&&this._30.equals(a)||void 0==this._30&&void 0==a)){void 0!=this._30&&$(this._30).off("."+this._229);var h=this._30;this._30=a;d(this);e(this,void 0==h&&a._93||void 0==a&&h._93||void 0!=h&&void 0!=a)}};n.prototype.get_Guid=function(){return this._229};n.prototype.equals=function(a){return this===a?!0:a instanceof n?
a._221===this._221&&this._356.equals(a._356):!1};n.prototype.getTile=function(a,d,b,e,f,g,k,l,n){function p(g){g.image=q;g.pos={x:a,y:d};g.size={width:b,height:e};g.scale=f;g.renderingSettings=s;void 0!=t&&(g.decodingSettings=t)}var q=this,s=this._8.clone(),t;void 0!=this._30&&(t=this._30.clone());return this._356._350(this._221,a,d,b,e,f,g,k,s,t,function(a){p(a);l&&l(a)},function(a){p(a);void 0!=a.fileId&&(q._0=100,q._277=100,q._212=96,q._343=96);n&&n(a)})};n.prototype.renderTiles=function(a,d,b,
e,f,g){function k(a){a.image=l;a.renderingSettings=n;void 0!=p&&(a.decodingSettings=p)}var l=this,n=this._8.clone(),p;void 0!=this._30&&(p=this._30.clone());return this._356._177(this._221,a,d,b,e,n,p,function(a){k(a);f&&f(a)},function(a){k(a);g&&g(a)})};n.prototype.getThumbnail=function(a,d,b,e,f,g){function k(b){b.image=l;b.width=a;b.height=d;b.renderingSettings=n;void 0!=p&&(b.decodingSettings=p)}var l=this,n=this._8.clone(),p;void 0!=this._30&&(p=this._30.clone());this._356._16(this._221,a,d,
b,e,n,p,function(a){k(a);void 0!=a.imageParam&&l._85(a.imageParam);f&&f(a)},function(a){k(a);g&&g(a)})};n.prototype.getImageInfo=function(a,b){function d(a){a.image=e;a.renderingSettings=f;void 0!=g&&(a.decodingSettings=g)}var e=this,f=this._8.clone(),g;void 0!=this._30&&(g=this._30.clone());return this._356._58(this._221,this._8,this._30,function(b){d(b);e._85(b);a&&a(b)},function(a){d(a);b&&b(a)})};n.prototype.getImageAsBase64String=function(a,b){function d(a){a.image=e;a.renderingSettings=f;void 0!=
g&&(a.decodingSettings=g)}var e=this,f=this._8.clone(),g;void 0!=this._30&&(g=this._30.clone());return this._356._45(this._221,f,g,function(b){d(b);a&&a(b)},function(a){d(a);b&&b(a)})};n.prototype._toObject=function(){return{imageId:this._356._15,pageIndex:this._221}};n.prototype._setToObject=function(){var a={};!1===this._296||this._8.isEmpty()||(a.renderingSettings=this._8._97());void 0!=this._30&&(a.decodingSettings=this._30._97());return a};n.prototype._get_IDG=function(){return this._126};n.prototype._change_IDG=
function(){this._126=l.WebImagingEnviromentJS.guid();this._343=this._212=this._277=this._0=void 0;$(this).triggerHandler("idg_changed")};n.prototype._85=function(a){if(void 0==this._0||void 0==this._277||void 0==this._212||void 0==this._343){this._0=Number(a.imageSize.width);this._277=Number(a.imageSize.height);this._212=Number(a.imageResolution.width);this._343=Number(a.imageResolution.height);this._296=a.isVector;try{this._307=new l.WebPixelFormatEnumJS(a.pixelFormat)}catch(b){this._307=new l.WebPixelFormatEnumJS(0)}}};
b.c(a,B);this._356=a;this._221=f;this._229=l.WebImagingEnviromentJS.guid();this._126=l.WebImagingEnviromentJS.guid();this._8=new t;k(this);this._30;this._0;this._277;this._212;this._343;this._307;this._296;delete n.prototype.decodingSettingsChanged;delete n.prototype.renderingSettingsChanged;delete n.prototype.idg_changed};q.defaultImageCollectionService=-1;var p=function(){function a(a){for(var b=a.imageInfos,c=[],h=[],f=0;f<b.length;f++){var g=b[f].imageId,k=c[g];void 0==k&&(k=new B(g),c[g]=k);
h.push(new n(k,b[f].pageIndex))}a.images=h}function f(a,e){var c={};b.ad(e,function(e){b.n(e);(0>e||e>=a._281.length)&&b.toe();void 0==c[e]&&(c[e]=1)});var h=[],f;for(f in c)h.push(Number(f));return h}function k(a,e,c){var h=!1,f=!1,g=!1;for(void 0==c._356._202&&(g=!0);e<a.length;e++){var k=a[e],l;a:{l=k;var n=c,p=!h;if(l._356.equals(n._356)&&(l._221===n._221&&b.te("Image already exists in collection."),p)){n._356=l._356;n._356._101=l._356._101;n._356._202=l._356._202;l=!0;break a}l=!1}l&&(g=f=h=
!0);f||c._356._101._63!==k._356._101._63||(c._356._101=k._356._101,f=!0);g||void 0==k._356._202||c._356._202._63!==k._356._202._63||(c._356._202=k._356._202,g=!0)}}function g(a,b){for(var c=-1,h=0;h<a._281.length;h++)if(a._281[h]._229==b){c=h;break}return c}p.prototype.changing=function(a,b){};p.prototype.changed=function(a,b){};p.prototype.get_Count=function(){return this._281.length};p.prototype.get_Image=function(a){b.n(a);if(0<=a&&a<this._281.length)return this._281[a];b.toe()};p.prototype.indexOf=
function(a){"string"!==typeof a&&b.c(a,n);return g(this,"string"===typeof a?a:a._229)};p.prototype.clear=function(){if(0!==this._281.length){var a={actionName:"clear",images:this.toArray()};this._99(a);this._281=[];this._141(a)}};p.prototype.add=function(a){this.insert(this._281.length,a)};p.prototype.addRange=function(a){this.insertRange(this._281.length,a)};p.prototype.insert=function(a,e){b.n(a);b.c(e,n);if(0<=a&&a<=this._281.length){k(this._281,0,e);var c={actionName:"insert",imageIndex:a,image:e};
this._99(c);this._281.splice(a,0,e);this._141(c)}else b.toe()};p.prototype.insertRange=function(a,e){var c=!0;e instanceof p&&(e=e._281,c=!1);b.n(a);c&&b.ac(e,n);if(0<=a&&a<=this._281.length){for(var h=e.length,c=e.concat(this._281),h=h-1;0<=h;h--)k(c,h+1,e[h]);c={actionName:"insertRange",imageIndex:a,images:e};this._99(c);for(h=0;h<e.length;h++)this._281.splice(a+h,0,e[h]);this._141(c)}else b.toe()};p.prototype.removeAt=function(a){b.n(a);if(0<=a&&a<this._281.length&&0!=this._281.length){var e={actionName:"removeAt",
imageIndex:a,image:this._281[a]};this._99(e);this._281.splice(a,1);this._141(e)}else b.toe()};p.prototype.remove=function(a){b.c(a,n);a=g(this,a._229);-1!==a?this.removeAt(a):b.te("Image does not exist.")};p.prototype.removeImages=function(a){var e=[],c=this;b.ad(a,function(a){b.c(a,n);a=g(c,a._229);-1!==a?e.push(a):b.te("Image does not exist.")});this.removeRange(e)};p.prototype.removeRange=function(a){a=f(this,a);for(var b=[],c=0;c<a.length;c++)b.push(this._281[a[c]]);b={actionName:"removeRange",
imagesIndexes:a,images:b};this._99(b);for(c=a.length-1;0<=c;c--)this._281.splice(a[c],1);this._141(b)};p.prototype.set=function(a,e){b.n(a);b.c(e,n);if(0<=a&&a<this._281.length&&0!=this._281.length){var c={actionName:"set",imageIndex:a,image:e,previousImage:this._281[a]};this._99(c);this._26=!1;this.removeAt(a);this.insert(a,e);this._26=!0;this._141(c)}else b.toe()};p.prototype.toArray=function(){return[].concat(this._281)};p.prototype.setRenderingSettings=function(a){b.c(a,t);for(var e=0;e<this._281.length;e++)this._281[e].set_RenderingSettings(a.clone())};
p.prototype.setDecodingSettings=function(a){void 0!=a&&b.c(a,x);if(void 0!=a)for(var e=0;e<this._281.length;e++)this._281[e].set_DecodingSettings(a.clone());else for(e=0;e<this._281.length;e++)this._281[e].set_DecodingSettings()};p.prototype.getImageFilesInfos=function(d,e,c,f){try{b.ad(d,b.s)}catch(g){b.te("fileUrls parameter must be an array of strings")}f=q.defaultImageCollectionService;e instanceof q&&(f=e);b.c(f,q,"Image collection service is not correct.");d=new s("GetImageFileInfo",function(b,
c,d){a(b);"function"===typeof e&&e(b,c,d)},c,{type:"POST",data:{fileIds:d}});return f.sendRequest(d)};p.prototype.openFile=function(a,e,c,f){b.s(a);return this.openFiles([a],e,c,f)};p.prototype.openFiles=function(a,b,c,f){b instanceof q&&(f=b);var g=this;return this.getImageFilesInfos(a,function(a,c,d){g.clear();g.addRange(a.images);"function"===typeof b&&b(a,c,d)},c,f)};p.prototype.saveState=function(a,e,c){void 0==c&&(c=q.defaultImageCollectionService);b.c(c,q,"Image collection service is not correct.");
for(var f=this.toArray(),g=[],k=0;k<f.length;k++){var l=f[k].get_Source();g.push({imageId:l._15,pageIndex:f[k]._221})}a=new s("SaveState",a,e,{type:"POST",data:{imageInfos:g}});return c.sendRequest(a)};p.prototype.loadState=function(d,e,c){void 0==c&&(c=q.defaultImageCollectionService);b.c(c,q,"Image collection service is not correct.");e=new s("LoadState",function(b,c,e){a(b);"function"===typeof d&&d(b,c,e)},e,{type:"POST",data:{}});return c.sendRequest(e)};p.prototype._99=function(a){this._26&&
$(this).triggerHandler("changing",a)};p.prototype._141=function(a){this._26&&$(this).triggerHandler("changed",a)};this._281=[];this._26=!0;delete p.prototype.changing;delete p.prototype.changed};l.pv=b;l.EnumGenerator=z;l.WebEnumItemBase=A;l.WebFlagsEnumItemBase=C;l.WebPropertyInfoJS=y;l.WebPropertyGridJS=H;l.WebRequestJS=s;l.WebCompositeRequestJS=D;l.WebServiceJS=q;l.WebServiceControllerJS=E;l.WebServiceHandlerJS=F;l.WebDecodingSettingsJS=x;l.WebRenderingSettingsJS=t;l.WebImageSourceJS=B;l.WebImageJS=
n;l.WebImageCollectionJS=p})(v.Shared||(v.Shared={}))})(Vintasoft||(Vintasoft={}));
