//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Areas.Contracts.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ContractEntities : DbContext
    {
        public ContractEntities()
            : base("name=ContractEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int spr_tblContractsDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblContractsDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblContractsInsert(Nullable<int> fldContractTypeId, Nullable<bool> fldNaghshOrgan, string fldTarikh, string fldShomare, string fldSubject, string fldTarikhEblagh, string fldShomareEblagh, Nullable<int> fldAshkhasId, Nullable<long> fldMablagh, Nullable<byte> fldSuplyMaterialsType, string fldStartDate, string fldEndDate, Nullable<long> fldMandePardakhtNashode, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc, Nullable<int> fldBudjeCodingId_Detail)
        {
            var fldContractTypeIdParameter = fldContractTypeId.HasValue ?
                new ObjectParameter("fldContractTypeId", fldContractTypeId) :
                new ObjectParameter("fldContractTypeId", typeof(int));
    
            var fldNaghshOrganParameter = fldNaghshOrgan.HasValue ?
                new ObjectParameter("fldNaghshOrgan", fldNaghshOrgan) :
                new ObjectParameter("fldNaghshOrgan", typeof(bool));
    
            var fldTarikhParameter = fldTarikh != null ?
                new ObjectParameter("fldTarikh", fldTarikh) :
                new ObjectParameter("fldTarikh", typeof(string));
    
            var fldShomareParameter = fldShomare != null ?
                new ObjectParameter("fldShomare", fldShomare) :
                new ObjectParameter("fldShomare", typeof(string));
    
            var fldSubjectParameter = fldSubject != null ?
                new ObjectParameter("fldSubject", fldSubject) :
                new ObjectParameter("fldSubject", typeof(string));
    
            var fldTarikhEblaghParameter = fldTarikhEblagh != null ?
                new ObjectParameter("fldTarikhEblagh", fldTarikhEblagh) :
                new ObjectParameter("fldTarikhEblagh", typeof(string));
    
            var fldShomareEblaghParameter = fldShomareEblagh != null ?
                new ObjectParameter("fldShomareEblagh", fldShomareEblagh) :
                new ObjectParameter("fldShomareEblagh", typeof(string));
    
            var fldAshkhasIdParameter = fldAshkhasId.HasValue ?
                new ObjectParameter("fldAshkhasId", fldAshkhasId) :
                new ObjectParameter("fldAshkhasId", typeof(int));
    
            var fldMablaghParameter = fldMablagh.HasValue ?
                new ObjectParameter("fldMablagh", fldMablagh) :
                new ObjectParameter("fldMablagh", typeof(long));
    
            var fldSuplyMaterialsTypeParameter = fldSuplyMaterialsType.HasValue ?
                new ObjectParameter("fldSuplyMaterialsType", fldSuplyMaterialsType) :
                new ObjectParameter("fldSuplyMaterialsType", typeof(byte));
    
            var fldStartDateParameter = fldStartDate != null ?
                new ObjectParameter("fldStartDate", fldStartDate) :
                new ObjectParameter("fldStartDate", typeof(string));
    
            var fldEndDateParameter = fldEndDate != null ?
                new ObjectParameter("fldEndDate", fldEndDate) :
                new ObjectParameter("fldEndDate", typeof(string));
    
            var fldMandePardakhtNashodeParameter = fldMandePardakhtNashode.HasValue ?
                new ObjectParameter("fldMandePardakhtNashode", fldMandePardakhtNashode) :
                new ObjectParameter("fldMandePardakhtNashode", typeof(long));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldBudjeCodingId_DetailParameter = fldBudjeCodingId_Detail.HasValue ?
                new ObjectParameter("fldBudjeCodingId_Detail", fldBudjeCodingId_Detail) :
                new ObjectParameter("fldBudjeCodingId_Detail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblContractsInsert", fldContractTypeIdParameter, fldNaghshOrganParameter, fldTarikhParameter, fldShomareParameter, fldSubjectParameter, fldTarikhEblaghParameter, fldShomareEblaghParameter, fldAshkhasIdParameter, fldMablaghParameter, fldSuplyMaterialsTypeParameter, fldStartDateParameter, fldEndDateParameter, fldMandePardakhtNashodeParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter, fldBudjeCodingId_DetailParameter);
        }
    
        public virtual int spr_tblContractsUpdate(Nullable<int> fldId, Nullable<int> fldContractTypeId, Nullable<bool> fldNaghshOrgan, string fldTarikh, string fldShomare, string fldSubject, string fldTarikhEblagh, string fldShomareEblagh, Nullable<int> fldAshkhasId, Nullable<long> fldMablagh, Nullable<byte> fldSuplyMaterialsType, string fldStartDate, string fldEndDate, Nullable<long> fldMandePardakhtNashode, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc, Nullable<int> fldBudjeCodingId_Detail)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldContractTypeIdParameter = fldContractTypeId.HasValue ?
                new ObjectParameter("fldContractTypeId", fldContractTypeId) :
                new ObjectParameter("fldContractTypeId", typeof(int));
    
            var fldNaghshOrganParameter = fldNaghshOrgan.HasValue ?
                new ObjectParameter("fldNaghshOrgan", fldNaghshOrgan) :
                new ObjectParameter("fldNaghshOrgan", typeof(bool));
    
            var fldTarikhParameter = fldTarikh != null ?
                new ObjectParameter("fldTarikh", fldTarikh) :
                new ObjectParameter("fldTarikh", typeof(string));
    
            var fldShomareParameter = fldShomare != null ?
                new ObjectParameter("fldShomare", fldShomare) :
                new ObjectParameter("fldShomare", typeof(string));
    
            var fldSubjectParameter = fldSubject != null ?
                new ObjectParameter("fldSubject", fldSubject) :
                new ObjectParameter("fldSubject", typeof(string));
    
            var fldTarikhEblaghParameter = fldTarikhEblagh != null ?
                new ObjectParameter("fldTarikhEblagh", fldTarikhEblagh) :
                new ObjectParameter("fldTarikhEblagh", typeof(string));
    
            var fldShomareEblaghParameter = fldShomareEblagh != null ?
                new ObjectParameter("fldShomareEblagh", fldShomareEblagh) :
                new ObjectParameter("fldShomareEblagh", typeof(string));
    
            var fldAshkhasIdParameter = fldAshkhasId.HasValue ?
                new ObjectParameter("fldAshkhasId", fldAshkhasId) :
                new ObjectParameter("fldAshkhasId", typeof(int));
    
            var fldMablaghParameter = fldMablagh.HasValue ?
                new ObjectParameter("fldMablagh", fldMablagh) :
                new ObjectParameter("fldMablagh", typeof(long));
    
            var fldSuplyMaterialsTypeParameter = fldSuplyMaterialsType.HasValue ?
                new ObjectParameter("fldSuplyMaterialsType", fldSuplyMaterialsType) :
                new ObjectParameter("fldSuplyMaterialsType", typeof(byte));
    
            var fldStartDateParameter = fldStartDate != null ?
                new ObjectParameter("fldStartDate", fldStartDate) :
                new ObjectParameter("fldStartDate", typeof(string));
    
            var fldEndDateParameter = fldEndDate != null ?
                new ObjectParameter("fldEndDate", fldEndDate) :
                new ObjectParameter("fldEndDate", typeof(string));
    
            var fldMandePardakhtNashodeParameter = fldMandePardakhtNashode.HasValue ?
                new ObjectParameter("fldMandePardakhtNashode", fldMandePardakhtNashode) :
                new ObjectParameter("fldMandePardakhtNashode", typeof(long));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldBudjeCodingId_DetailParameter = fldBudjeCodingId_Detail.HasValue ?
                new ObjectParameter("fldBudjeCodingId_Detail", fldBudjeCodingId_Detail) :
                new ObjectParameter("fldBudjeCodingId_Detail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblContractsUpdate", fldIdParameter, fldContractTypeIdParameter, fldNaghshOrganParameter, fldTarikhParameter, fldShomareParameter, fldSubjectParameter, fldTarikhEblaghParameter, fldShomareEblaghParameter, fldAshkhasIdParameter, fldMablaghParameter, fldSuplyMaterialsTypeParameter, fldStartDateParameter, fldEndDateParameter, fldMandePardakhtNashodeParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter, fldBudjeCodingId_DetailParameter);
        }
    
        public virtual int spr_tblContractTypeDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblContractTypeDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblContractTypeInsert(string fldTitle, Nullable<decimal> fldDarsadBimePeymankar, Nullable<decimal> fldDarsadBimeKarfarma, Nullable<decimal> fldDarsadAnjamKar, Nullable<decimal> fldDarsadZemanatName, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc)
        {
            var fldTitleParameter = fldTitle != null ?
                new ObjectParameter("fldTitle", fldTitle) :
                new ObjectParameter("fldTitle", typeof(string));
    
            var fldDarsadBimePeymankarParameter = fldDarsadBimePeymankar.HasValue ?
                new ObjectParameter("fldDarsadBimePeymankar", fldDarsadBimePeymankar) :
                new ObjectParameter("fldDarsadBimePeymankar", typeof(decimal));
    
            var fldDarsadBimeKarfarmaParameter = fldDarsadBimeKarfarma.HasValue ?
                new ObjectParameter("fldDarsadBimeKarfarma", fldDarsadBimeKarfarma) :
                new ObjectParameter("fldDarsadBimeKarfarma", typeof(decimal));
    
            var fldDarsadAnjamKarParameter = fldDarsadAnjamKar.HasValue ?
                new ObjectParameter("fldDarsadAnjamKar", fldDarsadAnjamKar) :
                new ObjectParameter("fldDarsadAnjamKar", typeof(decimal));
    
            var fldDarsadZemanatNameParameter = fldDarsadZemanatName.HasValue ?
                new ObjectParameter("fldDarsadZemanatName", fldDarsadZemanatName) :
                new ObjectParameter("fldDarsadZemanatName", typeof(decimal));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblContractTypeInsert", fldTitleParameter, fldDarsadBimePeymankarParameter, fldDarsadBimeKarfarmaParameter, fldDarsadAnjamKarParameter, fldDarsadZemanatNameParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblContractTypeSelect> spr_tblContractTypeSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblContractTypeSelect>("spr_tblContractTypeSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblContractTypeUpdate(Nullable<int> fldId, string fldTitle, Nullable<decimal> fldDarsadBimePeymankar, Nullable<decimal> fldDarsadBimeKarfarma, Nullable<decimal> fldDarsadAnjamKar, Nullable<decimal> fldDarsadZemanatName, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldTitleParameter = fldTitle != null ?
                new ObjectParameter("fldTitle", fldTitle) :
                new ObjectParameter("fldTitle", typeof(string));
    
            var fldDarsadBimePeymankarParameter = fldDarsadBimePeymankar.HasValue ?
                new ObjectParameter("fldDarsadBimePeymankar", fldDarsadBimePeymankar) :
                new ObjectParameter("fldDarsadBimePeymankar", typeof(decimal));
    
            var fldDarsadBimeKarfarmaParameter = fldDarsadBimeKarfarma.HasValue ?
                new ObjectParameter("fldDarsadBimeKarfarma", fldDarsadBimeKarfarma) :
                new ObjectParameter("fldDarsadBimeKarfarma", typeof(decimal));
    
            var fldDarsadAnjamKarParameter = fldDarsadAnjamKar.HasValue ?
                new ObjectParameter("fldDarsadAnjamKar", fldDarsadAnjamKar) :
                new ObjectParameter("fldDarsadAnjamKar", typeof(decimal));
    
            var fldDarsadZemanatNameParameter = fldDarsadZemanatName.HasValue ?
                new ObjectParameter("fldDarsadZemanatName", fldDarsadZemanatName) :
                new ObjectParameter("fldDarsadZemanatName", typeof(decimal));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblContractTypeUpdate", fldIdParameter, fldTitleParameter, fldDarsadBimePeymankarParameter, fldDarsadBimeKarfarmaParameter, fldDarsadAnjamKarParameter, fldDarsadZemanatNameParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblContractsSelect> spr_tblContractsSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblContractsSelect>("spr_tblContractsSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblTamdidDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTamdidDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblTamdidInsert(Nullable<int> fldContractId, Nullable<byte> fldTamdidTypeId, string fldTarikhPayan, Nullable<long> fldMablaghAfzayeshi, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc)
        {
            var fldContractIdParameter = fldContractId.HasValue ?
                new ObjectParameter("fldContractId", fldContractId) :
                new ObjectParameter("fldContractId", typeof(int));
    
            var fldTamdidTypeIdParameter = fldTamdidTypeId.HasValue ?
                new ObjectParameter("fldTamdidTypeId", fldTamdidTypeId) :
                new ObjectParameter("fldTamdidTypeId", typeof(byte));
    
            var fldTarikhPayanParameter = fldTarikhPayan != null ?
                new ObjectParameter("fldTarikhPayan", fldTarikhPayan) :
                new ObjectParameter("fldTarikhPayan", typeof(string));
    
            var fldMablaghAfzayeshiParameter = fldMablaghAfzayeshi.HasValue ?
                new ObjectParameter("fldMablaghAfzayeshi", fldMablaghAfzayeshi) :
                new ObjectParameter("fldMablaghAfzayeshi", typeof(long));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTamdidInsert", fldContractIdParameter, fldTamdidTypeIdParameter, fldTarikhPayanParameter, fldMablaghAfzayeshiParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblTamdidSelect> spr_tblTamdidSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblTamdidSelect>("spr_tblTamdidSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_tblTamdidTypesSelect> spr_tblTamdidTypesSelect(string fieldName, string value, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblTamdidTypesSelect>("spr_tblTamdidTypesSelect", fieldNameParameter, valueParameter, hParameter);
        }
    
        public virtual int spr_tblTamdidUpdate(Nullable<int> fldId, Nullable<int> fldContractId, Nullable<byte> fldTamdidTypeId, string fldTarikhPayan, Nullable<long> fldMablaghAfzayeshi, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldContractIdParameter = fldContractId.HasValue ?
                new ObjectParameter("fldContractId", fldContractId) :
                new ObjectParameter("fldContractId", typeof(int));
    
            var fldTamdidTypeIdParameter = fldTamdidTypeId.HasValue ?
                new ObjectParameter("fldTamdidTypeId", fldTamdidTypeId) :
                new ObjectParameter("fldTamdidTypeId", typeof(byte));
    
            var fldTarikhPayanParameter = fldTarikhPayan != null ?
                new ObjectParameter("fldTarikhPayan", fldTarikhPayan) :
                new ObjectParameter("fldTarikhPayan", typeof(string));
    
            var fldMablaghAfzayeshiParameter = fldMablaghAfzayeshi.HasValue ?
                new ObjectParameter("fldMablaghAfzayeshi", fldMablaghAfzayeshi) :
                new ObjectParameter("fldMablaghAfzayeshi", typeof(long));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTamdidUpdate", fldIdParameter, fldContractIdParameter, fldTamdidTypeIdParameter, fldTarikhPayanParameter, fldMablaghAfzayeshiParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual int spr_tblTazaminDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTazaminDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblTazaminInsert(Nullable<int> fldContractId, Nullable<int> fldWarrantyTypeId, Nullable<bool> fldTypeTamdid, string fldSepamNum, string fldTarikh, Nullable<long> fldMablagh, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc)
        {
            var fldContractIdParameter = fldContractId.HasValue ?
                new ObjectParameter("fldContractId", fldContractId) :
                new ObjectParameter("fldContractId", typeof(int));
    
            var fldWarrantyTypeIdParameter = fldWarrantyTypeId.HasValue ?
                new ObjectParameter("fldWarrantyTypeId", fldWarrantyTypeId) :
                new ObjectParameter("fldWarrantyTypeId", typeof(int));
    
            var fldTypeTamdidParameter = fldTypeTamdid.HasValue ?
                new ObjectParameter("fldTypeTamdid", fldTypeTamdid) :
                new ObjectParameter("fldTypeTamdid", typeof(bool));
    
            var fldSepamNumParameter = fldSepamNum != null ?
                new ObjectParameter("fldSepamNum", fldSepamNum) :
                new ObjectParameter("fldSepamNum", typeof(string));
    
            var fldTarikhParameter = fldTarikh != null ?
                new ObjectParameter("fldTarikh", fldTarikh) :
                new ObjectParameter("fldTarikh", typeof(string));
    
            var fldMablaghParameter = fldMablagh.HasValue ?
                new ObjectParameter("fldMablagh", fldMablagh) :
                new ObjectParameter("fldMablagh", typeof(long));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTazaminInsert", fldContractIdParameter, fldWarrantyTypeIdParameter, fldTypeTamdidParameter, fldSepamNumParameter, fldTarikhParameter, fldMablaghParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblTazaminSelect> spr_tblTazaminSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblTazaminSelect>("spr_tblTazaminSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblTazaminUpdate(Nullable<int> fldId, Nullable<int> fldContractId, Nullable<int> fldWarrantyTypeId, Nullable<bool> fldTypeTamdid, string fldSepamNum, string fldTarikh, Nullable<long> fldMablagh, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldContractIdParameter = fldContractId.HasValue ?
                new ObjectParameter("fldContractId", fldContractId) :
                new ObjectParameter("fldContractId", typeof(int));
    
            var fldWarrantyTypeIdParameter = fldWarrantyTypeId.HasValue ?
                new ObjectParameter("fldWarrantyTypeId", fldWarrantyTypeId) :
                new ObjectParameter("fldWarrantyTypeId", typeof(int));
    
            var fldTypeTamdidParameter = fldTypeTamdid.HasValue ?
                new ObjectParameter("fldTypeTamdid", fldTypeTamdid) :
                new ObjectParameter("fldTypeTamdid", typeof(bool));
    
            var fldSepamNumParameter = fldSepamNum != null ?
                new ObjectParameter("fldSepamNum", fldSepamNum) :
                new ObjectParameter("fldSepamNum", typeof(string));
    
            var fldTarikhParameter = fldTarikh != null ?
                new ObjectParameter("fldTarikh", fldTarikh) :
                new ObjectParameter("fldTarikh", typeof(string));
    
            var fldMablaghParameter = fldMablagh.HasValue ?
                new ObjectParameter("fldMablagh", fldMablagh) :
                new ObjectParameter("fldMablagh", typeof(long));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTazaminUpdate", fldIdParameter, fldContractIdParameter, fldWarrantyTypeIdParameter, fldTypeTamdidParameter, fldSepamNumParameter, fldTarikhParameter, fldMablaghParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblWarrantyTypeSelect> spr_tblWarrantyTypeSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblWarrantyTypeSelect>("spr_tblWarrantyTypeSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int spr_tblContractSignersDelete(Nullable<int> fldID, Nullable<int> fldUserID)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(int));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblContractSignersDelete", fldIDParameter, fldUserIDParameter);
        }
    
        public virtual int spr_tblContractSignersInsert(Nullable<int> fldContractId, Nullable<short> fldCompanyPostId, Nullable<int> fldEmpolyId, Nullable<int> fldPostEjraeeId, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc)
        {
            var fldContractIdParameter = fldContractId.HasValue ?
                new ObjectParameter("fldContractId", fldContractId) :
                new ObjectParameter("fldContractId", typeof(int));
    
            var fldCompanyPostIdParameter = fldCompanyPostId.HasValue ?
                new ObjectParameter("fldCompanyPostId", fldCompanyPostId) :
                new ObjectParameter("fldCompanyPostId", typeof(short));
    
            var fldEmpolyIdParameter = fldEmpolyId.HasValue ?
                new ObjectParameter("fldEmpolyId", fldEmpolyId) :
                new ObjectParameter("fldEmpolyId", typeof(int));
    
            var fldPostEjraeeIdParameter = fldPostEjraeeId.HasValue ?
                new ObjectParameter("fldPostEjraeeId", fldPostEjraeeId) :
                new ObjectParameter("fldPostEjraeeId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblContractSignersInsert", fldContractIdParameter, fldCompanyPostIdParameter, fldEmpolyIdParameter, fldPostEjraeeIdParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<spr_tblContractSignersSelect> spr_tblContractSignersSelect(string fieldName, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblContractSignersSelect>("spr_tblContractSignersSelect", fieldNameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblContractSignersUpdate(Nullable<int> fldId, Nullable<int> fldContractId, Nullable<short> fldCompanyPostId, Nullable<int> fldEmpolyId, Nullable<int> fldPostEjraeeId, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldIP, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldContractIdParameter = fldContractId.HasValue ?
                new ObjectParameter("fldContractId", fldContractId) :
                new ObjectParameter("fldContractId", typeof(int));
    
            var fldCompanyPostIdParameter = fldCompanyPostId.HasValue ?
                new ObjectParameter("fldCompanyPostId", fldCompanyPostId) :
                new ObjectParameter("fldCompanyPostId", typeof(short));
    
            var fldEmpolyIdParameter = fldEmpolyId.HasValue ?
                new ObjectParameter("fldEmpolyId", fldEmpolyId) :
                new ObjectParameter("fldEmpolyId", typeof(int));
    
            var fldPostEjraeeIdParameter = fldPostEjraeeId.HasValue ?
                new ObjectParameter("fldPostEjraeeId", fldPostEjraeeId) :
                new ObjectParameter("fldPostEjraeeId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblContractSignersUpdate", fldIdParameter, fldContractIdParameter, fldCompanyPostIdParameter, fldEmpolyIdParameter, fldPostEjraeeIdParameter, fldUserIdParameter, fldOrganIdParameter, fldIPParameter, fldDescParameter);
        }
    
        public virtual int spr_tblTanKhahGardanDelete(Nullable<int> fldId, Nullable<int> fldUserId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTanKhahGardanDelete", fldIdParameter, fldUserIdParameter);
        }
    
        public virtual int spr_tblTanKhahGardanInsert(Nullable<int> fldEmployeeId, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldEmployeeIdParameter = fldEmployeeId.HasValue ?
                new ObjectParameter("fldEmployeeId", fldEmployeeId) :
                new ObjectParameter("fldEmployeeId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTanKhahGardanInsert", fldEmployeeIdParameter, fldOrganIdParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblTanKhahGardanSelect> spr_tblTanKhahGardanSelect(string fieldname, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblTanKhahGardanSelect>("spr_tblTanKhahGardanSelect", fieldnameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblTanKhahGardanUpdate(Nullable<int> fldId, Nullable<int> fldEmployeeId, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldEmployeeIdParameter = fldEmployeeId.HasValue ?
                new ObjectParameter("fldEmployeeId", fldEmployeeId) :
                new ObjectParameter("fldEmployeeId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTanKhahGardanUpdate", fldIdParameter, fldEmployeeIdParameter, fldOrganIdParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int spr_tblTanKhahGardanUpdate_Status(Nullable<int> fldId, Nullable<bool> fldStatus, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldStatusParameter = fldStatus.HasValue ?
                new ObjectParameter("fldStatus", fldStatus) :
                new ObjectParameter("fldStatus", typeof(bool));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTanKhahGardanUpdate_Status", fldIdParameter, fldStatusParameter, fldOrganIdParameter, fldUserIdParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblContract_FactorSelect> spr_tblContract_FactorSelect(string fieldname, string value, Nullable<int> oganId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var oganIdParameter = oganId.HasValue ?
                new ObjectParameter("oganId", oganId) :
                new ObjectParameter("oganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblContract_FactorSelect>("spr_tblContract_FactorSelect", fieldnameParameter, valueParameter, oganIdParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_tblFactorDetailSelect> spr_tblFactorDetailSelect(string fieldname, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblFactorDetailSelect>("spr_tblFactorDetailSelect", fieldnameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual ObjectResult<spr_tblFactorMostaghelSelect> spr_tblFactorMostaghelSelect(string fieldname, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("organId", organId) :
                new ObjectParameter("organId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblFactorMostaghelSelect>("spr_tblFactorMostaghelSelect", fieldnameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblFactorInsert(string fldTarikh, string fldShomare, string fldShanaseMoadiyan, string fldSharhSanad, Nullable<int> fldContractId, Nullable<int> fldProjectId, Nullable<int> fldAshkhasId, Nullable<int> fldTankhahGroupId, Nullable<decimal> fldKasrBime, Nullable<decimal> fldKasrHosnAnjamKar, string fldShomareSabt, string fldCodeEghtesadi, string fldAddress, string fldTarikhVariz, string fldQrCode, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldTarikhParameter = fldTarikh != null ?
                new ObjectParameter("fldTarikh", fldTarikh) :
                new ObjectParameter("fldTarikh", typeof(string));
    
            var fldShomareParameter = fldShomare != null ?
                new ObjectParameter("fldShomare", fldShomare) :
                new ObjectParameter("fldShomare", typeof(string));
    
            var fldShanaseMoadiyanParameter = fldShanaseMoadiyan != null ?
                new ObjectParameter("fldShanaseMoadiyan", fldShanaseMoadiyan) :
                new ObjectParameter("fldShanaseMoadiyan", typeof(string));
    
            var fldSharhSanadParameter = fldSharhSanad != null ?
                new ObjectParameter("fldSharhSanad", fldSharhSanad) :
                new ObjectParameter("fldSharhSanad", typeof(string));
    
            var fldContractIdParameter = fldContractId.HasValue ?
                new ObjectParameter("fldContractId", fldContractId) :
                new ObjectParameter("fldContractId", typeof(int));
    
            var fldProjectIdParameter = fldProjectId.HasValue ?
                new ObjectParameter("fldProjectId", fldProjectId) :
                new ObjectParameter("fldProjectId", typeof(int));
    
            var fldAshkhasIdParameter = fldAshkhasId.HasValue ?
                new ObjectParameter("fldAshkhasId", fldAshkhasId) :
                new ObjectParameter("fldAshkhasId", typeof(int));
    
            var fldTankhahGroupIdParameter = fldTankhahGroupId.HasValue ?
                new ObjectParameter("fldTankhahGroupId", fldTankhahGroupId) :
                new ObjectParameter("fldTankhahGroupId", typeof(int));
    
            var fldKasrBimeParameter = fldKasrBime.HasValue ?
                new ObjectParameter("fldKasrBime", fldKasrBime) :
                new ObjectParameter("fldKasrBime", typeof(decimal));
    
            var fldKasrHosnAnjamKarParameter = fldKasrHosnAnjamKar.HasValue ?
                new ObjectParameter("fldKasrHosnAnjamKar", fldKasrHosnAnjamKar) :
                new ObjectParameter("fldKasrHosnAnjamKar", typeof(decimal));
    
            var fldShomareSabtParameter = fldShomareSabt != null ?
                new ObjectParameter("fldShomareSabt", fldShomareSabt) :
                new ObjectParameter("fldShomareSabt", typeof(string));
    
            var fldCodeEghtesadiParameter = fldCodeEghtesadi != null ?
                new ObjectParameter("fldCodeEghtesadi", fldCodeEghtesadi) :
                new ObjectParameter("fldCodeEghtesadi", typeof(string));
    
            var fldAddressParameter = fldAddress != null ?
                new ObjectParameter("fldAddress", fldAddress) :
                new ObjectParameter("fldAddress", typeof(string));
    
            var fldTarikhVarizParameter = fldTarikhVariz != null ?
                new ObjectParameter("fldTarikhVariz", fldTarikhVariz) :
                new ObjectParameter("fldTarikhVariz", typeof(string));
    
            var fldQrCodeParameter = fldQrCode != null ?
                new ObjectParameter("fldQrCode", fldQrCode) :
                new ObjectParameter("fldQrCode", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblFactorInsert", fldTarikhParameter, fldShomareParameter, fldShanaseMoadiyanParameter, fldSharhSanadParameter, fldContractIdParameter, fldProjectIdParameter, fldAshkhasIdParameter, fldTankhahGroupIdParameter, fldKasrBimeParameter, fldKasrHosnAnjamKarParameter, fldShomareSabtParameter, fldCodeEghtesadiParameter, fldAddressParameter, fldTarikhVarizParameter, fldQrCodeParameter, fldOrganIdParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblFactorSelect> spr_tblFactorSelect(string fieldname, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblFactorSelect>("spr_tblFactorSelect", fieldnameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblFactorUpdate(Nullable<int> fldId, string fldTarikh, string fldShomare, string fldShanaseMoadiyan, string fldSharhSanad, Nullable<int> fldProjectId, Nullable<int> fldAshkhasId, Nullable<int> fldTankhahGroupId, Nullable<decimal> fldKasrBime, Nullable<decimal> fldKasrHosnAnjamKar, string fldShomareSabt, string fldCodeEghtesadi, string fldAddress, string fldTarikhVariz, string fldQrCode, Nullable<int> fldOrganId, Nullable<int> fldUserId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldTarikhParameter = fldTarikh != null ?
                new ObjectParameter("fldTarikh", fldTarikh) :
                new ObjectParameter("fldTarikh", typeof(string));
    
            var fldShomareParameter = fldShomare != null ?
                new ObjectParameter("fldShomare", fldShomare) :
                new ObjectParameter("fldShomare", typeof(string));
    
            var fldShanaseMoadiyanParameter = fldShanaseMoadiyan != null ?
                new ObjectParameter("fldShanaseMoadiyan", fldShanaseMoadiyan) :
                new ObjectParameter("fldShanaseMoadiyan", typeof(string));
    
            var fldSharhSanadParameter = fldSharhSanad != null ?
                new ObjectParameter("fldSharhSanad", fldSharhSanad) :
                new ObjectParameter("fldSharhSanad", typeof(string));
    
            var fldProjectIdParameter = fldProjectId.HasValue ?
                new ObjectParameter("fldProjectId", fldProjectId) :
                new ObjectParameter("fldProjectId", typeof(int));
    
            var fldAshkhasIdParameter = fldAshkhasId.HasValue ?
                new ObjectParameter("fldAshkhasId", fldAshkhasId) :
                new ObjectParameter("fldAshkhasId", typeof(int));
    
            var fldTankhahGroupIdParameter = fldTankhahGroupId.HasValue ?
                new ObjectParameter("fldTankhahGroupId", fldTankhahGroupId) :
                new ObjectParameter("fldTankhahGroupId", typeof(int));
    
            var fldKasrBimeParameter = fldKasrBime.HasValue ?
                new ObjectParameter("fldKasrBime", fldKasrBime) :
                new ObjectParameter("fldKasrBime", typeof(decimal));
    
            var fldKasrHosnAnjamKarParameter = fldKasrHosnAnjamKar.HasValue ?
                new ObjectParameter("fldKasrHosnAnjamKar", fldKasrHosnAnjamKar) :
                new ObjectParameter("fldKasrHosnAnjamKar", typeof(decimal));
    
            var fldShomareSabtParameter = fldShomareSabt != null ?
                new ObjectParameter("fldShomareSabt", fldShomareSabt) :
                new ObjectParameter("fldShomareSabt", typeof(string));
    
            var fldCodeEghtesadiParameter = fldCodeEghtesadi != null ?
                new ObjectParameter("fldCodeEghtesadi", fldCodeEghtesadi) :
                new ObjectParameter("fldCodeEghtesadi", typeof(string));
    
            var fldAddressParameter = fldAddress != null ?
                new ObjectParameter("fldAddress", fldAddress) :
                new ObjectParameter("fldAddress", typeof(string));
    
            var fldTarikhVarizParameter = fldTarikhVariz != null ?
                new ObjectParameter("fldTarikhVariz", fldTarikhVariz) :
                new ObjectParameter("fldTarikhVariz", typeof(string));
    
            var fldQrCodeParameter = fldQrCode != null ?
                new ObjectParameter("fldQrCode", fldQrCode) :
                new ObjectParameter("fldQrCode", typeof(string));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblFactorUpdate", fldIdParameter, fldTarikhParameter, fldShomareParameter, fldShanaseMoadiyanParameter, fldSharhSanadParameter, fldProjectIdParameter, fldAshkhasIdParameter, fldTankhahGroupIdParameter, fldKasrBimeParameter, fldKasrHosnAnjamKarParameter, fldShomareSabtParameter, fldCodeEghtesadiParameter, fldAddressParameter, fldTarikhVarizParameter, fldQrCodeParameter, fldOrganIdParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_SelectGardeshMali_Contract> spr_SelectGardeshMali_Contract(Nullable<int> organId)
        {
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectGardeshMali_Contract>("spr_SelectGardeshMali_Contract", organIdParameter);
        }
    
        public virtual int spr_tblFactorDelete(Nullable<int> fldId, Nullable<int> fldUserId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblFactorDelete", fldIdParameter, fldUserIdParameter);
        }
    
        public virtual int spr_UpdateStatusFactor(Nullable<int> factorId, Nullable<bool> status, Nullable<int> userId)
        {
            var factorIdParameter = factorId.HasValue ?
                new ObjectParameter("factorId", factorId) :
                new ObjectParameter("factorId", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_UpdateStatusFactor", factorIdParameter, statusParameter, userIdParameter);
        }
    
        public virtual int spr_tblTankhah_GroupDelete(Nullable<int> fldId, Nullable<int> fldUserId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTankhah_GroupDelete", fldIdParameter, fldUserIdParameter);
        }
    
        public virtual int spr_tblTankhah_GroupInsert(Nullable<int> fldTankhahId, string fldTitle, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc, string fldIP)
        {
            var fldTankhahIdParameter = fldTankhahId.HasValue ?
                new ObjectParameter("fldTankhahId", fldTankhahId) :
                new ObjectParameter("fldTankhahId", typeof(int));
    
            var fldTitleParameter = fldTitle != null ?
                new ObjectParameter("fldTitle", fldTitle) :
                new ObjectParameter("fldTitle", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTankhah_GroupInsert", fldTankhahIdParameter, fldTitleParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<spr_tblTankhah_GroupSelect> spr_tblTankhah_GroupSelect(string fieldname, string value, Nullable<int> organId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var organIdParameter = organId.HasValue ?
                new ObjectParameter("OrganId", organId) :
                new ObjectParameter("OrganId", typeof(int));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_tblTankhah_GroupSelect>("spr_tblTankhah_GroupSelect", fieldnameParameter, valueParameter, organIdParameter, hParameter);
        }
    
        public virtual int spr_tblTankhah_GroupUpdate(Nullable<int> fldId, Nullable<int> fldTankhahId, string fldTitle, Nullable<int> fldUserId, Nullable<int> fldOrganId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldTankhahIdParameter = fldTankhahId.HasValue ?
                new ObjectParameter("fldTankhahId", fldTankhahId) :
                new ObjectParameter("fldTankhahId", typeof(int));
    
            var fldTitleParameter = fldTitle != null ?
                new ObjectParameter("fldTitle", fldTitle) :
                new ObjectParameter("fldTitle", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldOrganIdParameter = fldOrganId.HasValue ?
                new ObjectParameter("fldOrganId", fldOrganId) :
                new ObjectParameter("fldOrganId", typeof(int));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_tblTankhah_GroupUpdate", fldIdParameter, fldTankhahIdParameter, fldTitleParameter, fldUserIdParameter, fldOrganIdParameter, fldDescParameter, fldIPParameter);
        }
    }
}
