//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Areas.Contracts.Models
{
    using System;
    
    public partial class spr_tblContractSignersSelect
    {
        public int fldId { get; set; }
        public int fldContractId { get; set; }
        public Nullable<short> fldCompanyPostId { get; set; }
        public int fldEmpolyId { get; set; }
        public Nullable<int> fldPostEjraeeId { get; set; }
        public int fldUserId { get; set; }
        public int fldOrganId { get; set; }
        public string fldIP { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldName_family { get; set; }
        public string fldPost { get; set; }
    }
}
