//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Areas.Contracts.Models
{
    using System;
    
    public partial class spr_tblFactorDetailSelect
    {
        public int fldId { get; set; }
        public int fldHeaderId { get; set; }
        public long fldMablagh { get; set; }
        public long fldMablaghMaliyat { get; set; }
        public int fldCodingDetailId { get; set; }
        public int fldOrganId { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public string fldIP { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldSharhArtikl { get; set; }
        public bool fldTax { get; set; }
        public string fldTaxName { get; set; }
        public string fldTitle { get; set; }
    }
}
