//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Areas.Contracts.Models
{
    using System;
    
    public partial class spr_tblTanKhahGardanSelect
    {
        public int fldId { get; set; }
        public int fldEmployeeId { get; set; }
        public bool fldStatus { get; set; }
        public int fldOrganId { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIP { get; set; }
        public string fldStatusName { get; set; }
        public string fldName_Family { get; set; }
    }
}
