//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Areas.Contracts.Models
{
    using System;
    
    public partial class spr_tblFactorMostaghelSelect
    {
        public int fldId { get; set; }
        public int fldFactorId { get; set; }
        public Nullable<int> fldAshkhasId { get; set; }
        public Nullable<int> fldBudjeCodingId { get; set; }
        public int fldUserId { get; set; }
        public int fldOrganID { get; set; }
        public string fldIP { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public Nullable<int> fldTankhahGroupId { get; set; }
    }
}
