//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Areas.Contracts.Models
{
    using System;
    
    public partial class spr_tblFactorSelect
    {
        public int fldId { get; set; }
        public string fldTarikh { get; set; }
        public string fldShomare { get; set; }
        public string fldShanaseMoadiyan { get; set; }
        public bool fldStatus { get; set; }
        public int fldOrganId { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public string fldIP { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldstatusName { get; set; }
        public string fldSharhSanad { get; set; }
        public string fldNameContract { get; set; }
        public int fldContractId { get; set; }
        public string SellerName { get; set; }
        public string TitleProject { get; set; }
        public int fldAshkhasId { get; set; }
        public int fldProjeId { get; set; }
        public decimal fldKasrBime { get; set; }
        public decimal fldKasrHosnAnjamKar { get; set; }
        public string fldtarikhvariz { get; set; }
        public string fldQrCode { get; set; }
        public string fldNameTankhah { get; set; }
    }
}
