//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Areas.Contracts.Models
{
    using System;
    
    public partial class spr_tblTazaminSelect
    {
        public int fldId { get; set; }
        public int fldContractId { get; set; }
        public int fldWarrantyTypeId { get; set; }
        public bool fldTypeTamdid { get; set; }
        public string fldSepamNum { get; set; }
        public string fldTarikh { get; set; }
        public long fldMablagh { get; set; }
        public int fldUserId { get; set; }
        public int fldOrganId { get; set; }
        public string fldIP { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldTypeTamdidName { get; set; }
        public string fldSubject { get; set; }
        public string fldNameWarranty { get; set; }
        public int fldIsvalid { get; set; }
    }
}
