//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Areas.Contracts.Models
{
    using System;
    
    public partial class spr_tblContractsSelect
    {
        public int fldId { get; set; }
        public int fldContractTypeId { get; set; }
        public bool fldNaghshOrgan { get; set; }
        public string fldTarikh { get; set; }
        public string fldShomare { get; set; }
        public string fldSubject { get; set; }
        public string fldTarikhEblagh { get; set; }
        public string fldShomareEblagh { get; set; }
        public int fldAshkhasId { get; set; }
        public long fldMablagh { get; set; }
        public string fldStartDate { get; set; }
        public string fldEndDate { get; set; }
        public long fldMandePardakhtNashode { get; set; }
        public int fldUserId { get; set; }
        public int fldOrganId { get; set; }
        public string fldIP { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldNameTarfDovom { get; set; }
        public string fldNaghshName { get; set; }
        public string fldTypeTitle { get; set; }
        public byte fldSuplyMaterialsType { get; set; }
        public string fldSuplyMaterialsType_Name { get; set; }
        public string fldTarikhTamdid { get; set; }
        public int fldZamen { get; set; }
        public int fldValidDate { get; set; }
        public string fldTitleBudje { get; set; }
        public int fldBudjeCodingId_Detail { get; set; }
        public int fldTedadFactor { get; set; }
        public long fldMablaghfactor { get; set; }
        public long fldMaliyat { get; set; }
        public Nullable<long> fldMablaghVariz { get; set; }
    }
}
