//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Areas.Contracts.Models
{
    using System;
    
    public partial class spr_SelectGardeshMali_Contract
    {
        public string fldCode { get; set; }
        public string fldNameCoding { get; set; }
        public string fldTypeMande { get; set; }
        public Nullable<long> fldMande { get; set; }
    }
}
