//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Areas.Deceased.Models
{
    using System;
    
    public partial class spr_tblGhabrInfoSelect
    {
        public int fldId { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldNameFather { get; set; }
        public string fldBDate { get; set; }
        public string fldDeathDate { get; set; }
        public int fldUserId { get; set; }
        public int fldOrganId { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldObjectId { get; set; }
    }
}
