//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NewFMS.RasaKhazane {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="KhazaneServiceSoap", Namespace="http://tempuri.org/")]
    public partial class KhazaneService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReciveFishOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReciveCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadCodeHesabOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public KhazaneService() {
            this.Url = global::NewFMS.Properties.Settings.Default.NewFMS_RasaKhazane_KhazaneService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReciveFishCompletedEventHandler ReciveFishCompleted;
        
        /// <remarks/>
        public event ReciveCheckCompletedEventHandler ReciveCheckCompleted;
        
        /// <remarks/>
        public event LoadCodeHesabCompletedEventHandler LoadCodeHesabCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReciveFish", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReciveFish(string UserName, string Password, string FishId, string Hesab, FishDetial[] FishDetail, string MoadyName, string MoadyFamily, string MoadyCodeMeli, long MablaghFish, long MablaghGerdShode) {
            object[] results = this.Invoke("ReciveFish", new object[] {
                        UserName,
                        Password,
                        FishId,
                        Hesab,
                        FishDetail,
                        MoadyName,
                        MoadyFamily,
                        MoadyCodeMeli,
                        MablaghFish,
                        MablaghGerdShode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReciveFishAsync(string UserName, string Password, string FishId, string Hesab, FishDetial[] FishDetail, string MoadyName, string MoadyFamily, string MoadyCodeMeli, long MablaghFish, long MablaghGerdShode) {
            this.ReciveFishAsync(UserName, Password, FishId, Hesab, FishDetail, MoadyName, MoadyFamily, MoadyCodeMeli, MablaghFish, MablaghGerdShode, null);
        }
        
        /// <remarks/>
        public void ReciveFishAsync(string UserName, string Password, string FishId, string Hesab, FishDetial[] FishDetail, string MoadyName, string MoadyFamily, string MoadyCodeMeli, long MablaghFish, long MablaghGerdShode, object userState) {
            if ((this.ReciveFishOperationCompleted == null)) {
                this.ReciveFishOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReciveFishOperationCompleted);
            }
            this.InvokeAsync("ReciveFish", new object[] {
                        UserName,
                        Password,
                        FishId,
                        Hesab,
                        FishDetail,
                        MoadyName,
                        MoadyFamily,
                        MoadyCodeMeli,
                        MablaghFish,
                        MablaghGerdShode}, this.ReciveFishOperationCompleted, userState);
        }
        
        private void OnReciveFishOperationCompleted(object arg) {
            if ((this.ReciveFishCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReciveFishCompleted(this, new ReciveFishCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReciveCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReciveCheck(string UserName, string Password, Checks Checks) {
            object[] results = this.Invoke("ReciveCheck", new object[] {
                        UserName,
                        Password,
                        Checks});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReciveCheckAsync(string UserName, string Password, Checks Checks) {
            this.ReciveCheckAsync(UserName, Password, Checks, null);
        }
        
        /// <remarks/>
        public void ReciveCheckAsync(string UserName, string Password, Checks Checks, object userState) {
            if ((this.ReciveCheckOperationCompleted == null)) {
                this.ReciveCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReciveCheckOperationCompleted);
            }
            this.InvokeAsync("ReciveCheck", new object[] {
                        UserName,
                        Password,
                        Checks}, this.ReciveCheckOperationCompleted, userState);
        }
        
        private void OnReciveCheckOperationCompleted(object arg) {
            if ((this.ReciveCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReciveCheckCompleted(this, new ReciveCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadCodeHesab", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sp_tblSarfasMoinSelect[] LoadCodeHesab(string UserName, string Password) {
            object[] results = this.Invoke("LoadCodeHesab", new object[] {
                        UserName,
                        Password});
            return ((Sp_tblSarfasMoinSelect[])(results[0]));
        }
        
        /// <remarks/>
        public void LoadCodeHesabAsync(string UserName, string Password) {
            this.LoadCodeHesabAsync(UserName, Password, null);
        }
        
        /// <remarks/>
        public void LoadCodeHesabAsync(string UserName, string Password, object userState) {
            if ((this.LoadCodeHesabOperationCompleted == null)) {
                this.LoadCodeHesabOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadCodeHesabOperationCompleted);
            }
            this.InvokeAsync("LoadCodeHesab", new object[] {
                        UserName,
                        Password}, this.LoadCodeHesabOperationCompleted, userState);
        }
        
        private void OnLoadCodeHesabOperationCompleted(object arg) {
            if ((this.LoadCodeHesabCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadCodeHesabCompleted(this, new LoadCodeHesabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FishDetial {
        
        private int radifField;
        
        private string codeHesabField;
        
        private long mablaghField;
        
        private string descField;
        
        /// <remarks/>
        public int radif {
            get {
                return this.radifField;
            }
            set {
                this.radifField = value;
            }
        }
        
        /// <remarks/>
        public string CodeHesab {
            get {
                return this.codeHesabField;
            }
            set {
                this.codeHesabField = value;
            }
        }
        
        /// <remarks/>
        public long Mablagh {
            get {
                return this.mablaghField;
            }
            set {
                this.mablaghField = value;
            }
        }
        
        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sp_tblSarfasMoinSelect {
        
        private string fldSafaslMoinIdField;
        
        private string fldOnvanHesabField;
        
        private string fldGroupIdField;
        
        private string fldSarfaslIdField;
        
        private string fldMoinIdField;
        
        private string fldTafsiliIdField;
        
        private string fldTafsiliId1Field;
        
        private string fldTafsiliId2Field;
        
        /// <remarks/>
        public string fldSafaslMoinId {
            get {
                return this.fldSafaslMoinIdField;
            }
            set {
                this.fldSafaslMoinIdField = value;
            }
        }
        
        /// <remarks/>
        public string fldOnvanHesab {
            get {
                return this.fldOnvanHesabField;
            }
            set {
                this.fldOnvanHesabField = value;
            }
        }
        
        /// <remarks/>
        public string fldGroupId {
            get {
                return this.fldGroupIdField;
            }
            set {
                this.fldGroupIdField = value;
            }
        }
        
        /// <remarks/>
        public string fldSarfaslId {
            get {
                return this.fldSarfaslIdField;
            }
            set {
                this.fldSarfaslIdField = value;
            }
        }
        
        /// <remarks/>
        public string fldMoinId {
            get {
                return this.fldMoinIdField;
            }
            set {
                this.fldMoinIdField = value;
            }
        }
        
        /// <remarks/>
        public string fldTafsiliId {
            get {
                return this.fldTafsiliIdField;
            }
            set {
                this.fldTafsiliIdField = value;
            }
        }
        
        /// <remarks/>
        public string fldTafsiliId1 {
            get {
                return this.fldTafsiliId1Field;
            }
            set {
                this.fldTafsiliId1Field = value;
            }
        }
        
        /// <remarks/>
        public string fldTafsiliId2 {
            get {
                return this.fldTafsiliId2Field;
            }
            set {
                this.fldTafsiliId2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckDetail {
        
        private string codeHesabField;
        
        private long mablaghField;
        
        /// <remarks/>
        public string CodeHesab {
            get {
                return this.codeHesabField;
            }
            set {
                this.codeHesabField = value;
            }
        }
        
        /// <remarks/>
        public long Mablagh {
            get {
                return this.mablaghField;
            }
            set {
                this.mablaghField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Checks {
        
        private string bankField;
        
        private string shenaseBankField;
        
        private string shobeField;
        
        private string shobeAddressField;
        
        private string codeShobeField;
        
        private long mablaghField;
        
        private string tarikhVosolField;
        
        private string babatField;
        
        private string checkNumField;
        
        private string hesabDaramadiField;
        
        private string nameField;
        
        private string familyField;
        
        private string codeMeliField;
        
        private bool typeShakhsField;
        
        private CheckDetail[] checkDetailField;
        
        /// <remarks/>
        public string Bank {
            get {
                return this.bankField;
            }
            set {
                this.bankField = value;
            }
        }
        
        /// <remarks/>
        public string ShenaseBank {
            get {
                return this.shenaseBankField;
            }
            set {
                this.shenaseBankField = value;
            }
        }
        
        /// <remarks/>
        public string Shobe {
            get {
                return this.shobeField;
            }
            set {
                this.shobeField = value;
            }
        }
        
        /// <remarks/>
        public string ShobeAddress {
            get {
                return this.shobeAddressField;
            }
            set {
                this.shobeAddressField = value;
            }
        }
        
        /// <remarks/>
        public string CodeShobe {
            get {
                return this.codeShobeField;
            }
            set {
                this.codeShobeField = value;
            }
        }
        
        /// <remarks/>
        public long Mablagh {
            get {
                return this.mablaghField;
            }
            set {
                this.mablaghField = value;
            }
        }
        
        /// <remarks/>
        public string TarikhVosol {
            get {
                return this.tarikhVosolField;
            }
            set {
                this.tarikhVosolField = value;
            }
        }
        
        /// <remarks/>
        public string Babat {
            get {
                return this.babatField;
            }
            set {
                this.babatField = value;
            }
        }
        
        /// <remarks/>
        public string CheckNum {
            get {
                return this.checkNumField;
            }
            set {
                this.checkNumField = value;
            }
        }
        
        /// <remarks/>
        public string HesabDaramadi {
            get {
                return this.hesabDaramadiField;
            }
            set {
                this.hesabDaramadiField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Family {
            get {
                return this.familyField;
            }
            set {
                this.familyField = value;
            }
        }
        
        /// <remarks/>
        public string CodeMeli {
            get {
                return this.codeMeliField;
            }
            set {
                this.codeMeliField = value;
            }
        }
        
        /// <remarks/>
        public bool TypeShakhs {
            get {
                return this.typeShakhsField;
            }
            set {
                this.typeShakhsField = value;
            }
        }
        
        /// <remarks/>
        public CheckDetail[] checkDetail {
            get {
                return this.checkDetailField;
            }
            set {
                this.checkDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ReciveFishCompletedEventHandler(object sender, ReciveFishCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReciveFishCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReciveFishCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ReciveCheckCompletedEventHandler(object sender, ReciveCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReciveCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReciveCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void LoadCodeHesabCompletedEventHandler(object sender, LoadCodeHesabCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadCodeHesabCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadCodeHesabCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sp_tblSarfasMoinSelect[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sp_tblSarfasMoinSelect[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591