//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFMS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://46.100.105.149/Revenue/Services/ServiseToRevenueSystems.asmx")]
        public string NewFMS_HesabRayan_ServiseToRevenueSystems {
            get {
                return ((string)(this["NewFMS_HesabRayan_ServiseToRevenueSystems"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1461/KhazaneService.asmx")]
        public string NewFMS_RasaKhazane_KhazaneService {
            get {
                return ((string)(this["NewFMS_RasaKhazane_KhazaneService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:24204/BimeSRV.asmx")]
        public string NewFMS_Bime_BimeSRV {
            get {
                return ((string)(this["NewFMS_Bime_BimeSRV"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8089/ContractService.svc")]
        public string NewFMS_WCF_Contract_ContractService {
            get {
                return ((string)(this["NewFMS_WCF_Contract_ContractService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.34:8089/AutomationService.svc")]
        public string NewFMS_WCF_Automation_AutomationService {
            get {
                return ((string)(this["NewFMS_WCF_Automation_AutomationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.34:8089/CommonService.svc")]
        public string NewFMS_WCF_Common_CommonService {
            get {
                return ((string)(this["NewFMS_WCF_Common_CommonService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.34:8089/AccountingService.svc")]
        public string NewFMS_WCF_Accounting_AccountingService {
            get {
                return ((string)(this["NewFMS_WCF_Accounting_AccountingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.34:8089/ChekService.svc")]
        public string NewFMS_WCF_Chek_ChekService {
            get {
                return ((string)(this["NewFMS_WCF_Chek_ChekService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.34:8089/AnbarAmvalService.svc")]
        public string NewFMS_WCF_AnbarAmval_AnbarAmvalService {
            get {
                return ((string)(this["NewFMS_WCF_AnbarAmval_AnbarAmvalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.34:8089/DaramadService.svc")]
        public string NewFMS_WCF_Daramad_DaramadService {
            get {
                return ((string)(this["NewFMS_WCF_Daramad_DaramadService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.34:8089/CommonService.svc")]
        public string NewFMS_WCF_FMS_CommonService {
            get {
                return ((string)(this["NewFMS_WCF_FMS_CommonService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.34:8089/WebServiceFormula.asmx")]
        public string NewFMS_FormulaService_WebServiceFormula {
            get {
                return ((string)(this["NewFMS_FormulaService_WebServiceFormula"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.33:8096/Comon_PayService.svc")]
        public string NewFMS_WCF_Common_Pay_Comon_PayService {
            get {
                return ((string)(this["NewFMS_WCF_Common_Pay_Comon_PayService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.34:8089/ArchiveService.svc")]
        public string NewFMS_WCF_Archive_ArchiveService {
            get {
                return ((string)(this["NewFMS_WCF_Archive_ArchiveService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.34:8089/DeceasedService.svc")]
        public string NewFMS_WCF_Deceased_DeceasedService {
            get {
                return ((string)(this["NewFMS_WCF_Deceased_DeceasedService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.34:8089/BudgetService.svc")]
        public string NewFMS_WCF_Budget_BudgetService {
            get {
                return ((string)(this["NewFMS_WCF_Budget_BudgetService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.33:8096/PayRolService.svc")]
        public string NewFMS_WCF_PayRoll_PayRolService {
            get {
                return ((string)(this["NewFMS_WCF_PayRoll_PayRolService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.34:8089/PersoneliService.svc")]
        public string NewFMS_WCF_Personeli_PersoneliService {
            get {
                return ((string)(this["NewFMS_WCF_Personeli_PersoneliService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.34:8089/WeighService.svc")]
        public string NewFMS_WCF_Weigh_WeighService {
            get {
                return ((string)(this["NewFMS_WCF_Weigh_WeighService"]));
            }
        }
    }
}
